steps:
  - name: 'europe-west1-docker.pkg.dev/connectedcars-build/cloudbuilder-wrapper/master'
    args: ['--skip-push', '--update-url=https://build-api.connectedcars.io/cloudbuilder']
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'
timeout: 3600s

