import { Make } from '../constants/make'
import { Model } from '../constants/model'
import { getModel } from './get-model'

type Testcase = {
  vin: string
  result: string | null
  name?: string
  modelCode?: string
}

function addVinToTest(vin: string): (a: Omit<Testcase, 'vin'>) => Testcase {
  return test => ({
    vin,
    ...test
  })
}

const cases = [
  ...[
    { name: 'VW Touran CL 1,4TSI 150HK DSG7 BMT 110kW', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'MOVE UP! 1,0MPI 60HK 5G BMT ', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'VW PASSAT VAR COMF. 1,6TDI 105HK 6G', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW POLO COMF 1,6TDI 90HK 5G BMT 66KW', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'VW move up 1,0MPI 60HK 5G BMT', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'Tiguan', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'VW Golf Var Allstar 1,4TSI 125HK 6G BMT', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf ', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Sharan HL 2,0TDI 184hk DSG6 BMT SCR 135k', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'ID.3', result: Model[Make.VOLKSWAGEN]['ID.3'] },
    { name: 'ID.4', result: Model[Make.VOLKSWAGEN]['ID.4'] },
    { name: 'ID.5', result: Model[Make.VOLKSWAGEN]['ID.5'] },
    { name: 'ID.7', result: Model[Make.VOLKSWAGEN]['ID.7'] },
    { name: 'ID.Buzz', result: Model[Make.VOLKSWAGEN]['ID.Buzz'] },
    { name: 'ID. 3', result: Model[Make.VOLKSWAGEN]['ID.3'] },
    { name: 'ID. 4', result: Model[Make.VOLKSWAGEN]['ID.4'] },
    { name: 'ID. 5', result: Model[Make.VOLKSWAGEN]['ID.5'] },
    { name: 'ID. 7', result: Model[Make.VOLKSWAGEN]['ID.7'] },
    { name: 'ID. Buzz', result: Model[Make.VOLKSWAGEN]['ID.Buzz'] },
    { name: 'Taos', result: Model[Make.VOLKSWAGEN].TAOS },
    { name: 'up!', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'Volkswagen CC', result: Model[Make.VOLKSWAGEN].CC },
    { name: 'California', result: Model[Make.VOLKSWAGEN].CALIFORNIA },
    { name: 'Grand California', result: Model[Make.VOLKSWAGEN].GRAND_CALIFORNIA },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'TRP PROLINE P-U DH 102HK 340', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'TRP PROLINE SKÅP 102HK 300', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'TRP KOM 150HK TDI DSG', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'TRP PROLINE P-U EH 102HK 340', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T5 CHASSIS LANG 2,0 TDI 140 HK BMT 6G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Kort Enka 2,0TDI 84hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW T6 Kort Enka 2,0TDI 84hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T5 CHASSIS LANG 2,0 TDI 140 HK BMT DSG7', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T5 CHASSIS LANG 2,0 TDI 140 HK BMT DSG7', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'TOURAN 1,6 TDi', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Touran ', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Passat Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'TIGUAN 2,0 BMT SPORT 4M 130 TDI D7A', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'VOLKSWAGEN TIGUAN 2.0 SPORT4M103 ', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'T6 Kort Kassevogn 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Passat', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Up!', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'Golf Wagon 1.6 CLBM 81 fTDIM5F', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'TOURAN CL 1,4TSI 150HK DSG7 BMT', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'JETTA 1,6 HL', result: Model[Make.VOLKSWAGEN].JETTA },
    { name: 'VW ID.3 1st Plus 204HK AUT1 Performance', result: Model[Make.VOLKSWAGEN]['ID.3'] },
    { name: 'Golf', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW GOLF VAR R-LINE 1,4TSI 150HK DSG7 BMT', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'polo', result: Model[Make.VOLKSWAGEN].POLO },
    { name: ' Touran', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'GOLF LIMO 1,4 TSI 122 HK', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Passat Variant 1,4 Tsi Aut.', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Touran 1.4 Highl 125 TSID7F', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Passat CC', result: Model[Make.VOLKSWAGEN].CC },
    { name: 'VW T6 Lang KSV 2,0 TDI 204 hk DSG 4MOTION', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Beetle', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'VW high up! 1,0TSI 90HK 5G', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'VW T6 Lang Doka 2,0TDI 150hk 6G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'JETTA', result: Model[Make.VOLKSWAGEN].JETTA },
    { name: 'Golf 7, 1.4TSI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Touran HL 2,0TDI', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'E-Golf', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'MOVE UP! 1,0MPI 60HK 5G BMT 44KW', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'Tiguan', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Arteon R-Line 2,0 TDI 110 kW (150 hv) DSG', result: Model[Make.VOLKSWAGEN].ARTEON },
    { name: 'Volkswagen Tiguan TDI', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'PASSAT WAG. CLE85 118 D7F ', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Scirocco', result: Model[Make.VOLKSWAGEN].SCIROCCO },
    { name: 'Golf 1.2 TLBMT 77 TSI M6F', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Crafter 35 2,0 TDI 130kW', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'MOVE UP! 1,0MPI 60HK 5G⇥', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'Crafter 2,0 177 HK Automat', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'Passat 1,9 Tdi Man Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Volkswagen Touran 1,6 Tdi Bmt', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'vw Touareg', result: Model[Make.VOLKSWAGEN].TOUAREG },
    { name: 'Up', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'VW T6 Lang Startline 2,0 TDI 102 5 Gear', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'vw touran', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW T6 Lang Enkeltkabine Alulad 2,0 TDI 102', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Golf Variant', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW GOLF VAR TREND 1,6TDI 105HK 5G BMT 77KW', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW BORA 2,0 115 HK 85 KW', result: Model[Make.VOLKSWAGEN].BORA },
    { name: 'VW Tiguan', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'VW TIGUAN 2,0 TDI 140 HK', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Tiguan Highline plus', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'GOLF MATCH TDI BMT', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Touran Caycaf', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Golf 2,0 R', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW TIGUAN 2,0 BMT SPORT TDIM6F', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Tiguan Comfortline PLUS 2,0TDI 150HK DSG7 SCR  ', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'golf 1,9 trend', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golfr32', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf 7 1,4', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW T6 Lang Startline 2,0 TDI 84 5 Gear', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW Crafter ALU L4 Enka 35 TDI 102HK 6G FWD', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW Crafter ALUL4 Doka35 3UATDI102HK 6G FWD', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW T6 Lang Doka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'vw passat', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Volkswagen Touran', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW T6 Kombi Lang 2,0 TDI 150 hk DSG7', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Kombi Kort 2,0 TDI 150 hk DSG', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Kombi Lang Varebil 2,0TDI 150hk 6g 4M', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Kort Startline 2,0 TDI 84 5 Gear', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'vw up', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'VW T6 Kombi Lang 2,0 TDI 150 hk DSG7 4MOT', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Golf 1,2', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW T6 Kort Startline 2,0 TDI 102 5 Gear', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW POLO', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'VW T6 Kombi Kort 2,0 TSI 204 hk DSG7', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'PASSAT WAG. CLBMT 100 M6F', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'CADDY MAXI WVHIGH 125 CRD6AT', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'tiguan 2.0', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Vw Polo 1,2 BMT', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'Vw Golf 2,0 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Touran comfl 2,0 COMFO 103 TDID6F', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VOLKSWAGEN UP¤ 1.0 MOVE 55 M5F', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'PASSAT WAG. CLB 103 D6F', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW T6 Chassis Zugkopf 2,0 TDI 204 DSG7', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Golf Cabriolet 1,6 Tdi', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'TOUAREG HYBRI 245 SI A8A', result: Model[Make.VOLKSWAGEN].TOUAREG },
    { name: 'GOLF 1.4 HLBM 92 TSI M6F', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW T6 Chassis Lang Dobbeltkabine DAN 2,0 TD', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Passat 2.0 tdi', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'TOURAN 1.6BMTTREND 77 TDIM6F', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW Tiguan Comfortline PLUS 2,0 TDI 150 HK 110 kW DSG7', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Tiguan 2.0 Tsi 180 4motion Dsg7', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Vw Touran 2,0 TDI 140 HK', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Phaeton 4M5-sea 171fTDIA6A', result: Model[Make.VOLKSWAGEN].PHAETON },
    { name: 'VW T6 Kort Kassevogn', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Passat V Conf 1,9TDI 105hk DPF', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW T6 Chassis Lang Dobb.kab 2,0 TD', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Tiguan 2,0 TDI', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Volkswagen Beetle 1.2 Tsi 105 Hk 77 Kw', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'Touareg', result: Model[Make.VOLKSWAGEN].TOUAREG },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Tiguan 2.0BMTSPORT4M130 TDID7A', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'BEETLE CAB LIFE 1,4TSI 150HK DSG7 BMT', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'GOLF VII 1,6 TDI 110 HK BM ST.CAR', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'T6', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Lang Enka 2,0TSI 150hk 6G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Transporter T6 2.0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Touran 2,0', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Touran 1.6 Tdi Bmt 105 Hk Dsg', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T6 Kort Enka 2,0TDI 84hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Phaeton', result: Model[Make.VOLKSWAGEN].PHAETON },
    { name: 'VW T6 Lang Startline 2,0 TDI 150HK 6G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'GOLF 1.2 CLBMT 63 TSI M5F', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Passat Variant 2,0 tdi', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Golf 2.0 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Transporter T6 2.0 TDI BMT 4MOTION (204hk)', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Tiguan 2.0 TDI 4MOTION (190hk)', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Transporter T6 2.0 TDI BMT (150hk)', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Transporter T5 2.0 TDI Pickup (140hk)', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW Polo CL 1,0TSI 95HK 5G', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'golf plus', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf E-golf', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Volkswagen Golf 7 1.2 Tsi', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Volkswagen Touran 1,6 trend', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW Golf Limo 1,4 TSI Allstar', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'GOLF PLUS TSICOMFO 118 M6F', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Volkswagen Golf', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Volkswagen Touran 1.6 Tdi Bmt 105 Hk Dsg 7', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Volkswagen Caddy 2.0 T', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'VW Tiguan CL PLUS 2,0TDI 150HK DSG7', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Volkswagen UP! 1,0', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'Polo 1,4 Trendline', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'Golf Varint', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf, 1,6 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Polo HL 1,0TSI 115HK DSG7', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'vw golf', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf 1,2 TSI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW move up! 1,0MPI 60HK 5G', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'VW T6 CARAVELLE LANG CL 2,0 TDI 150', result: Model[Make.VOLKSWAGEN].CARAVELLE },
    { name: 'Transporter T6 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW GOLF 2.0 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Caddy 2.0 TDI', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'Polo van 1,4 TDI', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'VW Touran CL 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'vw golf 1,4 tsi', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Crafter 2.0 TDI', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW Tiguan 2.0 110 TDI', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Caddy 2,0 TDI', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'TOUAREG 3.0 TDI AUT', result: Model[Make.VOLKSWAGEN].TOUAREG },
    { name: 'Touran 2,o TDI', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW Golf HL 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Crafter 2,0 TDI', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW Tiguan Highline PLUS 2,0TDI 150HK DSG7', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'Transporter T6 2.0 TDI 150kW', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW GOLF SPORTWAGEN', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Passat Variant 2,0 TDI DSG', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Crafter 35 2,0 TDI 120kW', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'scirocco 2,0 sport tdi', result: Model[Make.VOLKSWAGEN].SCIROCCO },
    { name: 'Volkswagen Polo 1,6 TDI', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'Touran 2,0 TDI', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'TOUAREG BMT V6TDI 150 TDIA8A', result: Model[Make.VOLKSWAGEN].TOUAREG },
    { name: 'VW Passat Variant R-Line 4Motion 240 HK', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW Golf Variant 1.6 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Passat Variant 2,0', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Passat GTE Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW Passat Variant 2,0 TDI', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW CRAFTER CHASSISL3 35 TDI 177HK AUT8G FWD', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'Transporter T6 2.0 TDI 110kw DSG', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW POLO 1,2 TSI 90HK', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'VW Passat Var CL Premium 1,5TSI 150HK DSG7', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Golf 1,0 cLBM TSI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf Sportsvan', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Passat 2,0 tdi Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'New Beetle', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'Transporter T6 2.0 TDI 110kW', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW TIGUAN SPORT 2,0TDI 140HK DSG7 BMT 4M', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'VOLKSWAGEN TOURAN 1.6BMTHIGHL 77 TDID7F', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'Arteon', result: Model[Make.VOLKSWAGEN].ARTEON },
    { name: 'Caddy Maxi 2.0 TDI', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'VW T6 Kort Kassevogn 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW Touran HL 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'CADDY VAN 1,6TDI 75 HK 55 KW 5 TRINS BMT', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'VW Polo CL Connect 1,0TSI 95HK 5G', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'polo 1,2', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'VW T6 KaKR', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Crafter, chassi', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'Crafter Skåp', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'Caddy Maxi', result: Model[Make.VOLKSWAGEN].CADDY },
    { name: 'Crafter Chassi', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'Golf  Alltrack', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Crafter', result: Model[Make.VOLKSWAGEN].CRAFTER },
    { name: 'VW Arteon Elegance 2,0TSI 190HK DSG7', result: Model[Make.VOLKSWAGEN].ARTEON },
    { name: 'Passat 2,0 tdi', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'VW Beetle Cab', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'Golf 1,4 TSI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Beetle Cabriolet', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'VW T6 Caravelle', result: Model[Make.VOLKSWAGEN].CARAVELLE },
    { name: 'TOURAN 2.0 COMFORTLINE', result: Model[Make.VOLKSWAGEN].TOURAN },
    { name: 'VW Beetle Cariolet', result: Model[Make.VOLKSWAGEN].BEETLE },
    { name: 'Golf 1,4', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Golf GTI 2,0TSI 120 HK', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Golf GTI 2,0TSI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Volkswagen Golf Variant', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VOLKSWAGEN TIGUAN 2.0 HLBMT4M 132TSID7A', result: Model[Make.VOLKSWAGEN].TIGUAN },
    { name: 'VW fresh up! 1,0MPI 60HK 5G BMT 44kW', result: Model[Make.VOLKSWAGEN].UP },
    { name: 'PASSAT WAG. CLBMT 176 TDID7A            ', result: Model[Make.VOLKSWAGEN].PASSAT },
    { name: 'Golf Variant 1,0 BlueMotion Technology', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'VW Polo CL 1,0TSI 95HK DSG7', result: Model[Make.VOLKSWAGEN].POLO },
    { name: 'Golf GTI', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Golf 1,0', result: Model[Make.VOLKSWAGEN].GOLF },
    { name: 'Transporter', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T-ROC STYLE 1,0TSI 115HK', result: Model[Make.VOLKSWAGEN].TROC },
    { name: 'T-Roc Sport 2,0TSI 190HK DSG7 4M', result: Model[Make.VOLKSWAGEN].TROC },
    { name: 'T-Roc Style 1,0TSI 115HK 6G', result: Model[Make.VOLKSWAGEN].TROC },
    { name: 'Transporter T5 2.0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Volkswagen T-Roc', result: Model[Make.VOLKSWAGEN].TROC },
    { name: 'VW T-Roc Style 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].TROC },
    { name: 'Transporter skåp', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW T-Cross Life 1,0TSI 115HK DSG7', result: Model[Make.VOLKSWAGEN].TCROSS },
    { name: 'VW T-Cross Life 1,0TSI 95HK 5G', result: Model[Make.VOLKSWAGEN].TCROSS },
    { name: 'VW Transporter T5GP', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Transporter 2.0 TDI 75kw', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'Sharan succ. HLBMT 130 CRD6F', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'Caravelle', result: Model[Make.VOLKSWAGEN].CARAVELLE },
    { name: 'Sharan 2,0 TDI', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'VW Sharan', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'VW Sharan 2,0 tdi dsg 170 hk', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'Sharan', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'Amarok 3.0 TDI', result: Model[Make.VOLKSWAGEN].AMAROK },
    { name: 'Amarok 2.0 TDI', result: Model[Make.VOLKSWAGEN].AMAROK },
    { name: 'Amarok 3.0 V6', result: Model[Make.VOLKSWAGEN].AMAROK },
    { name: 'Caravelle 2,0 TDI', result: Model[Make.VOLKSWAGEN].CARAVELLE },
    { name: 'Multivan 2,0 TDI', result: Model[Make.VOLKSWAGEN].MULTIVAN },
    { name: 'VW SHARAN HLBMT 162 TSID6F', result: Model[Make.VOLKSWAGEN].SHARAN },
    { name: 'VW T5 CHASSIS LANG 2,0 TDI 140HK BMT 4MOT', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
    { name: 'VW TaigO HK STAT', result: Model[Make.VOLKSWAGEN].TAIGO },
    { name: 'VW gOL-SAvEiRo', result: Model[Make.VOLKSWAGEN].GOL_SAVEIRO },
    { name: 'Volkswagen Teramont 2.0L S', result: Model[Make.VOLKSWAGEN].TERAMONT },
    { name: 'VW cROSs SporT 2', result: Model[Make.VOLKSWAGEN].CROSS_SPORT },
    { name: 'VW cROSs FoX 2', result: Model[Make.VOLKSWAGEN].CROSS_FOX },
    { name: 'VW goL', result: Model[Make.VOLKSWAGEN].GOL },
    { name: 'VW NiVuS', result: Model[Make.VOLKSWAGEN].NIVUS },
    { name: 'VW SAvEiRo', result: Model[Make.VOLKSWAGEN].SAVEIRO },
    { name: 'VW TaIgUN 3', result: Model[Make.VOLKSWAGEN].TAIGUN },
    { name: 'VW VeNtO', result: Model[Make.VOLKSWAGEN].VENTO },
    { name: 'VW ViRtUs', result: Model[Make.VOLKSWAGEN].VIRTUS }
  ].map(addVinToTest('WVWAAAAAAAA123456')),

  ...[
    { name: 'Skoda Octavia', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Octavia HB Style 1,4 TSI 150 HK DSG', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Superb Combi Style 2,0 TDI 150 hk DSG', result: Model[Make.SKODA].SUPERB },
    { name: 'Superb', result: Model[Make.SKODA].SUPERB },
    { name: 'Octavia', result: Model[Make.SKODA].OCTAVIA },
    { name: 'Citigo', result: Model[Make.SKODA].CITIGO },
    { name: 'SKODA OCTAVIA COMBI ELEGANCE 2,0 TDI 150 HK', result: Model[Make.SKODA].OCTAVIA },
    { name: 'Skoda Citigo 1,0', result: Model[Make.SKODA].CITIGO },
    { name: 'fabia', result: Model[Make.SKODA].FABIA },
    { name: 'Yeti Ambition', result: Model[Make.SKODA].YETI },
    { name: 'YETI', result: Model[Make.SKODA].YETI },
    { name: 'Superb 2.0 TDI 140HK Combi', result: Model[Make.SKODA].SUPERB },
    { name: 'Octavia Combi 1,6 TDI Aut.', result: Model[Make.SKODA].OCTAVIA },
    { name: 'Superb Combi 2.0 Tdi 170 Hk Stationcar Dsg', result: Model[Make.SKODA].SUPERB },
    { name: 'Skoda Yeti', result: Model[Make.SKODA].YETI },
    { name: 'Citigo 1.0 Mpi 75 Hk 3-dørs Hatchback', result: Model[Make.SKODA].CITIGO },
    { name: 'rapid', result: Model[Make.SKODA].RAPID },
    { name: 'Superb Combi 2.0 TDI 190HK', result: Model[Make.SKODA].SUPERB },
    { name: 'Octavia Scout 2,0 TDI', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA FABIA', result: Model[Make.SKODA].FABIA },
    { name: 'superb l og k', result: Model[Make.SKODA].SUPERB },
    { name: 'SKODA Rapid Spaceback Tour de France 1,0 TSI 9', result: Model[Make.SKODA].RAPID },
    { name: 'Superb Combi 2,0 Tdi Dsg 190hk', result: Model[Make.SKODA].SUPERB },
    { name: 'Octavia Scout', result: Model[Make.SKODA].OCTAVIA },
    { name: 'NY FABIA COMBI AMBITION 1,0 TSI 110 HK D', result: Model[Make.SKODA].FABIA },
    { name: 'Skoda Octavia RS 2,0 Tdi Aut.', result: Model[Make.SKODA].OCTAVIA },
    { name: 'RAPID SPACEBACK AMBITION 1,0 TSI 95 HK', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA Rapid Hatchback Style 1,0 TSI 110 hk DSG', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA Rapid Hatchback ICE 1,0 TSI 110 hk DSG', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA Rapid Hatchback ICE 1,0 TSI 95 hk', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA RAPID SPACEBACK AMBITION 1,0 TSI 95 HK', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA Spaceback Rapid Tour 1,0 95 hk.', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA Rapid Spaceback 1,0 TSI 95 HK', result: Model[Make.SKODA].RAPID },
    { name: 'SKODA Citigo Fresh 1,0 MPI 60 hk', result: Model[Make.SKODA].CITIGO },
    { name: 'Skoda Superb', result: Model[Make.SKODA].SUPERB },
    { name: 'SKODA Fabia FL Ambition 1,0 MPI 75 hk', result: Model[Make.SKODA].FABIA },
    { name: 'SKODA Octavia Combi Style 2,0 TSI 190 hk DSG', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Fabia Hatchback Ambition 1,0 TSI 95 hk', result: Model[Make.SKODA].FABIA },
    { name: 'SKODA Superb Combi Style 1,4 TSI 150 hk DSG', result: Model[Make.SKODA].SUPERB },
    { name: 'SKODA Ny Fabia Combi Ambition 1,0 TSI 95 hk', result: Model[Make.SKODA].FABIA },
    { name: 'SKODA OCTAVIA HB RS 2,0 TSI 220HK', result: Model[Make.SKODA].OCTAVIA },
    { name: 'RAPID SPB AMB TD85/1.6 M5F', result: Model[Make.SKODA].RAPID },
    { name: 'CITIGO ELEGA 55/1.0 5-S', result: Model[Make.SKODA].CITIGO },
    { name: 'SKODA CITIGO ACTIVE GREENTEC 1.0 60HK', result: Model[Make.SKODA].CITIGO },
    { name: 'SKODA Octavia Combi Style 1,0 TSI 115 hk 85 kW', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Octavia Combi Business Line 2,0 TDI 150', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Superb Combi Business Edition 2,0 TDI 15', result: Model[Make.SKODA].SUPERB },
    { name: 'SKODA OCTAVIA COMBI AMBITION 1,6 TDI 105 HK', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Octavia HN B-Line+ 1,5 TSI 150 hk DSG', result: Model[Make.SKODA].OCTAVIA },
    { name: 'SKODA Citigo Style Sport 1,0 MPI 60 hk', result: Model[Make.SKODA].CITIGO },
    { name: 'SKODA FABIA COMBI GREENLINE 1,2 CR - 55 KW', result: Model[Make.SKODA].FABIA },
    { name: 'SKODA Ny Fabia Combi Style Tour 1,0 TSI 95 hk', result: Model[Make.SKODA].FABIA },
    { name: 'Skoda Octavia Combi 2,0 TDI', result: Model[Make.SKODA].OCTAVIA },
    { name: 'Skoda Rapid 1,0', result: Model[Make.SKODA].RAPID },
    { name: 'Skoda Kodiaq', result: Model[Make.SKODA].KODIAQ },
    { name: 'SKODA Kodiaq Style 2,0 TDI 150 hk 4x4', result: Model[Make.SKODA].KODIAQ },
    { name: 'Skoda Karoq', result: Model[Make.SKODA].KAROQ },
    { name: 'SKODA Karoq Style 1,5 TSI 150 hk DSG', result: Model[Make.SKODA].KAROQ }
  ].map(addVinToTest('TMBAAAAAAAA123456')),

  ...[
    { name: 'TOLEDO STYLE 1,2 TSI 105HK 6 G', result: Model[Make.SEAT].TOLEDO },
    { name: 'SEAT Ny Ibiza 5D Style ', result: Model[Make.SEAT].IBIZA },
    { name: 'ATECA', result: Model[Make.SEAT].ATECA },
    { name: 'SEAT Ny Ibiza 5D Style ', result: Model[Make.SEAT].IBIZA },
    { name: 'ATECA', result: Model[Make.SEAT].ATECA },
    { name: 'SEAT Ny Ibiza FR 1,5 TSI EVO 150HK 6G', result: Model[Make.SEAT].IBIZA },
    { name: 'Seat Ateca 2.0 Tdi 190 Hk 140 Kw 5-dørs 4wd Dsg6', result: Model[Make.SEAT].ATECA },
    { name: 'Seat Ateca 1,4 TSI', result: Model[Make.SEAT].ATECA },
    { name: 'Saet Ateca 1,5 TSI 150', result: Model[Make.SEAT].ATECA },
    { name: 'Ibiza Style', result: Model[Make.SEAT].IBIZA },
    { name: 'Seat Ateca', result: Model[Make.SEAT].ATECA },
    { name: 'Seat Ateca Exultance 1.4TSP', result: Model[Make.SEAT].ATECA },
    { name: 'Ibiza', result: Model[Make.SEAT].IBIZA },
    { name: 'Arona', result: Model[Make.SEAT].ARONA },
    { name: 'SEAT Arona Xcellence 1,6 TDI 95HK DSG7', result: Model[Make.SEAT].ARONA },
    { name: 'SEAT ARONA', result: Model[Make.SEAT].ARONA },
    { name: 'LEON', result: Model[Make.SEAT].LEON },
    { name: 'Leon 2.0 Tsi 280 Hk 206 Kw St. Car Dsg6', result: Model[Make.SEAT].LEON },
    { name: 'SEAT LEON', result: Model[Make.SEAT].LEON },
    { name: 'Leon 2,0 TDI', result: Model[Make.SEAT].LEON },
    { name: 'SEAT Leon ST 1,6 TDI DSG STYLE', result: Model[Make.SEAT].LEON },
    { name: 'Seat Leon FR 2,0 TSI', result: Model[Make.SEAT].LEON },
    { name: 'Seat Leon St.car.', result: Model[Make.SEAT].LEON },
    { name: 'SEAT Leon ST Style Premium 1,6 TDI 115HK DSG7', result: Model[Make.SEAT].LEON },
    { name: 'SEAT Leon Sport Tourer ST 1.2 TSI DSG', result: Model[Make.SEAT].LEON },
    { name: 'SEAT Tarraco XC 7S 2,0 TSI 190HK 4x4 DSG7', result: Model[Make.SEAT].TARRACO },
    { name: 'SEAT Tarraco XC 7S 2,0 TDI 150HK 6G', result: Model[Make.SEAT].TARRACO },
    { name: 'SEAT Tarraco Xcellence 2,0 TSI 190HK 4x4 DSG7', result: Model[Make.SEAT].TARRACO },
    { name: 'SEAT Tarraco XC 7S 1,5 TSI 150HK 6G', result: Model[Make.SEAT].TARRACO },
    { name: 'SEAT ALTEA XL STYLANCE 1.8 TSI 160HK', result: Model[Make.SEAT].ALTEA },
    { name: 'Alhambra', result: Model[Make.SEAT].ALHAMBRA },
    { name: 'SEAT BoRn', result: Model[Make.SEAT].BORN }
  ].map(addVinToTest('VSSAAAAAAAA123456')),

  ...[
    { name: 'a4', result: Model[Make.AUDI].A4 },
    { name: 'Audi A3', result: Model[Make.AUDI].A3 },
    { name: 'Audi S3', result: Model[Make.AUDI].A3 },
    { name: 'Audi RS5', result: Model[Make.AUDI].A5 },
    { name: 'Audi Q7', result: Model[Make.AUDI].Q7 },
    { name: 'Audi SQ7', result: Model[Make.AUDI].Q7 },
    { name: 'S3', result: Model[Make.AUDI].A3 },
    { name: 'A6', result: Model[Make.AUDI].A6 },
    { name: 'A4 2,0 Tdi Avant', result: Model[Make.AUDI].A4 },
    { name: 'A4', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 AVA.Q. TDI2.0 I4130 A7S', result: Model[Make.AUDI].A4 },
    { name: 'Audi A7', result: Model[Make.AUDI].A7 },
    { name: 'Audi A4 AVANT TDI2.0', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 AVANT TDI 2.0', result: Model[Make.AUDI].A4 },
    { name: 'A4 Avant 2.0 TDI', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 AVANT TDI2.0 I4105 A8M', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 AVANT TDI2.0 I4130 A8M', result: Model[Make.AUDI].A4 },
    { name: 'a4 Avant', result: Model[Make.AUDI].A4 },
    { name: '8K5CSH A4 Avant TDI 2,0', result: Model[Make.AUDI].A4 },
    { name: 'A4 Avant 3.0 Tdi 204 Hk 5-dørs Multitronic', result: Model[Make.AUDI].A4 },
    { name: 'A4 Sal.', result: Model[Make.AUDI].A4 },
    { name: 'A4 AVANT TDI2.0 I4130 M6S', result: Model[Make.AUDI].A4 },
    { name: 'A4 2,0 Tdi Avant.', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 AVANT TDI2.0 I4130 M6S', result: Model[Make.AUDI].A4 },
    { name: 'Audi A6 Avant 2.8 V6 150Kw A8M', result: Model[Make.AUDI].A6 },
    { name: 'Audi A4 AVANT TDI2.0 I4110 M6S', result: Model[Make.AUDI].A4 },
    { name: 'A6 Avant 3.0 Tdi 218 Hk 5-dørs S Tronic', result: Model[Make.AUDI].A6 },
    { name: 'AUDI A6 AVANT 3,0 TDI 218 HK 160 KW 7 TRINS S', result: Model[Make.AUDI].A6 },
    { name: 'Audi A4 Avant 2,0 Tdi Aut.', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 Avant', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 Avant TDI2.0 105 KW', result: Model[Make.AUDI].A4 },
    { name: ' Audi A4 Avant 2,0 Tfsi Quattro', result: Model[Make.AUDI].A4 },
    { name: 'A4 Cabrio 2,0', result: Model[Make.AUDI].A4 },
    { name: 'AUDI A4 AVANT 1,8T 163HK 5 GEAR MAN.', result: Model[Make.AUDI].A4 },
    { name: 'AUDI A6 LIMOUSINE 3,0 TDI 218 HK 160 KW 7 TRI .', result: Model[Make.AUDI].A6 },
    { name: 'AUDI A4 AVA.Q. TDI2.0', result: Model[Make.AUDI].A4 },
    { name: 'AUDI A5 COUPÉ 1,8 TFSI 177 HK 130 KW 8 TRINS', result: Model[Make.AUDI].A5 },
    { name: 'Audi A6 2,0 TDI', result: Model[Make.AUDI].A6 },
    { name: 'Audi A4 Avant 1,8', result: Model[Make.AUDI].A4 },
    { name: 'A4 Avant 2,0 TDI', result: Model[Make.AUDI].A4 },
    { name: 'audi a4 avant 2.0 tdi', result: Model[Make.AUDI].A4 },
    { name: 'A5 Coupé 1,8 TFSI', result: Model[Make.AUDI].A5 },
    { name: 'Audi A4 Avant Business 40 TDI 190 HK S tro', result: Model[Make.AUDI].A4 },
    { name: 'AUDI RS 5 COUPÉ 4,2 FSI 450 HK 331 KW QUATTRO', result: Model[Make.AUDI].A5 },
    { name: 'Audi a4 lim.', result: Model[Make.AUDI].A4 },
    { name: 'Audi A6', result: Model[Make.AUDI].A6 },
    { name: 'Audi A4 Avant 2.0 Tdi 177 Hk 5-dørs Multitronic', result: Model[Make.AUDI].A4 },
    { name: 'Audi A6 Avant 3,0 TDi', result: Model[Make.AUDI].A6 },
    { name: 'A4 AVANT TDI2.0 I4105 A8M', result: Model[Make.AUDI].A4 },
    { name: 'A4 Avant quattro S-line 2.0 TDI 140kw190ps', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 Avant Sport 2,0 TFSI 190 HK S tro', result: Model[Make.AUDI].A4 },
    { name: 'AUDI A4 SAL. 2,0 TDI A8M', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 Avant 2,0 TDi', result: Model[Make.AUDI].A4 },
    { name: 'Audi A5 Coupe', result: Model[Make.AUDI].A5 },
    { name: 'Audi A4 2,0 TDI', result: Model[Make.AUDI].A4 },
    { name: 'Audi A4 TDI 3,0', result: Model[Make.AUDI].A4 },
    { name: 'A4 3,0 Tdi', result: Model[Make.AUDI].A4 },
    { name: 'S5 Sportback 3,0 TFSI 333 HK', result: Model[Make.AUDI].A5 },
    { name: 'S5 Sportback 3,0 TFSI 333 HK 245 KW QUAT', result: Model[Make.AUDI].A5 },
    { name: 'Audi S5 Cabriolet', result: Model[Make.AUDI].A5 },
    { name: 'AUDI RS 5 CABRIOLET 4,2 FSI 450 HK 331 KW QUA', result: Model[Make.AUDI].A5 },
    { name: 'Audi S5 CAB.', result: Model[Make.AUDI].A5 },
    { name: 'A5 Sportb TDI2.0', result: Model[Make.AUDI].A5 },
    { name: 'A3', result: Model[Make.AUDI].A3 },
    { name: 'AUDI RS Q3 2,5 TFSI 310 HK 228 KW QUATTRO 7 T', result: Model[Make.AUDI].Q3 },
    { name: 'Audi A3 Sportsback 1,6', result: Model[Make.AUDI].A3 },
    { name: 'Q7', result: Model[Make.AUDI].Q7 },
    { name: 'Q5', result: Model[Make.AUDI].Q5 },
    { name: 'AUDI A5 SPB QTDI2.0 I4130 A7S', result: Model[Make.AUDI].A5 },
    { name: 'Audi A3 Sportback', result: Model[Make.AUDI].A3 },
    { name: 'Audi Rs Q3 Performance 2.5 Tfsi 367 Hk 5-dørs Quattro S Tronic', result: Model[Make.AUDI].Q3 },
    { name: 'Audi Q4 Attitude 40  e-tron', result: Model[Make.AUDI].Q4_ETRON },
    { name: 'Audi Q6 Attitude 40  e-trOn', result: Model[Make.AUDI].Q6_ETRON },
    { name: 'SQ5', result: Model[Make.AUDI].Q5 },
    { name: 'A5 CABRIOLET 1,8 TFSI 177 HK 130 KW 8 TR', result: Model[Make.AUDI].A5 },
    { name: 'A5', result: Model[Make.AUDI].A5 },
    { name: 'Audi A3', result: Model[Make.AUDI].A3 },
    { name: 'AUDI Q5 3,0 TDI AUT.', result: Model[Make.AUDI].Q5 },
    { name: 'AUDI RS Q3 2,5 TFSI 340 HK S TRON', result: Model[Make.AUDI].Q3 },
    { name: 'Audi Q8 50 TDI qua 286 HK tip', result: Model[Make.AUDI].Q8 },
    { name: 'Audi e-tron 50 TDI qua RS Q8 286 HK tip', result: Model[Make.AUDI].Q8_ETRON },
    { name: 'Audi Q8 50 TDI qua e-Tron 286 HK tip', result: Model[Make.AUDI].Q8_ETRON },
    { name: 'Audi rsQ8 50 TDI qua e-Tron 286 HK tip', result: Model[Make.AUDI].Q8_ETRON },
    { name: 'Audi e-tRON rsQ8 50 TDI qua e-tron 286 HK tip', result: Model[Make.AUDI].Q8_ETRON },
    { name: 'AUDI Q7', result: Model[Make.AUDI].Q7 },
    { name: 'A5 Cabriolet 1,8 TFSI', result: Model[Make.AUDI].A5 },
    { name: 'Audi Q5 3,0 TDI', result: Model[Make.AUDI].Q5 },
    { name: 'Audi A3 SB Sp. Lim. 35 TDI 150 HK S tro', result: Model[Make.AUDI].A3 },
    { name: 'Audi Q5', result: Model[Make.AUDI].Q5 },
    { name: 'Audi Q8', result: Model[Make.AUDI].Q8 },
    { name: 'AUDI Q7 3,0 TDI 211HK QUATTRO TIPTRONIC EU4 (2009)', result: Model[Make.AUDI].Q7 },
    { name: 'AUDI A3 SPORTBACK AMBIENTE 1,4 TFSI 140 HK 10', result: Model[Make.AUDI].A3 },
    { name: 'Audi Q2', result: Model[Make.AUDI].Q2 },
    { name: 'Audi A3 SB Sp. Lim. 35 TFSI 150 HK S tro', result: Model[Make.AUDI].A3 },
    { name: 'Audi A5 SB Sport 40 TDI 190 HK S tro', result: Model[Make.AUDI].A5 },
    { name: 'Audi A5', result: Model[Make.AUDI].A5 },
    { name: 'AUDI Q5 QUAT. 3,0 TDI V6', result: Model[Make.AUDI].Q5 },
    { name: 'A5 Cabriolet', result: Model[Make.AUDI].A5 },
    { name: 'Audi Q3 Adv. PRE 35 TFSI 150 HK S tro', result: Model[Make.AUDI].Q3 },
    { name: 'AUDI RS 4 AVANT 4,2 FSI 450 HK 331 KW QUATTRO', result: Model[Make.AUDI].A4 },
    { name: 'Audi A5, 1,8 TFSI', result: Model[Make.AUDI].A5 },
    { name: 'Audi RS 3 Sportback 2,5TFSI 367hk S-tron qu', result: Model[Make.AUDI].A3 },
    { name: 'Audi RS7 SPORTB. Q4.0 V8412 A8 Audi RS7 SPORTB. Q4.0 V8412 A8', result: Model[Make.AUDI].A7 },
    { name: 'AUDI A7 SPORTBACK 3,0 TFSI QUA 333 HK S TRO', result: Model[Make.AUDI].A7 },
    { name: 'S7 Sportback 4,0 TFSI', result: Model[Make.AUDI].A7 },
    { name: 'Audi RS 3 2,5 TFSI', result: Model[Make.AUDI].A3 },
    { name: 'Audi RS6 Avant 4,0 FSI 550 HK', result: Model[Make.AUDI].A6 },
    { name: 'AUDI RS 6 AVANT 4,0 TFSI 560 HK 412 KW QUATTR', result: Model[Make.AUDI].A6 }
  ].map(addVinToTest('WAUAAAAAAAA123456')),

  ...[
    { name: 'Expert 1.6 Bluehdi 115 Hk L2', result: Model[Make.PEUGEOT].EXPERT },
    { name: 'Peugeot Partner L1 BlueHDi 75', result: Model[Make.PEUGEOT].PARTNER },
    { name: 'Peugeot Partner', result: Model[Make.PEUGEOT].PARTNER },
    { name: 'Peugeot Expert 2.0 Bluehdi 120 Hk L3', result: Model[Make.PEUGEOT].EXPERT },
    { name: 'Peugeot Partner Van 1.6 Bluehdi 100 Hk L2', result: Model[Make.PEUGEOT].PARTNER },
    { name: 'PEUGEOT EXPERT BlueHDi 120 L3', result: Model[Make.PEUGEOT].EXPERT },
    { name: 'Partner Van ⇥1,6 E-hdi L1', result: Model[Make.PEUGEOT].PARTNER },
    { name: 'Expert Varebil G9 2,0 Hdi 128 Hk L1h1', result: Model[Make.PEUGEOT].EXPERT },
    { name: 'Peugeot e-2008', result: Model[Make.PEUGEOT].E_2008 },
    { name: 'Peugeot 2008', result: Model[Make.PEUGEOT][2008] },
    { name: 'Peugeot 3008', result: Model[Make.PEUGEOT][3008] }
  ].map(addVinToTest('VF3AAAAAAAA123456')),

  ...[
    { name: 'Ford C-max', result: Model[Make.FORD].C_MAX },
    { name: 'Ford Transit', result: Model[Make.FORD].TRANSIT },
    { name: 'Ford Focus', result: Model[Make.FORD].FOCUS },
    { name: 'Ford S-Max', result: Model[Make.FORD].S_MAX },
    { name: 'Ford fiesTA', result: Model[Make.FORD].FIESTA },
    { name: 'Ford Mustang Mach-e', result: Model[Make.FORD].MUSTANG_MACH_E },
    { name: 'Ford Transit 2.2 Tdci (140 Hk) 350m Van Fwd Manuel', result: Model[Make.FORD].TRANSIT },
    { name: 'Ford Transit 2.2 Tdci (140 Hk) Kassevogn Man.', result: Model[Make.FORD].TRANSIT },
    { name: 'Ford Transit Custom 2.2 Tdci (100 Hk) 270 L1 Van Forhjulstræk Manuel', result: Model[Make.FORD].TRANSIT },
    { name: 'Ny C-max 2.0 tdci (170 Hk) Van Forhjulstræk Automatisk', result: Model[Make.FORD].C_MAX },
    { name: 'C-max Van 1,6 Tdci', result: Model[Make.FORD].C_MAX },
    { name: 'Focus C-max 1,6', result: Model[Make.FORD].C_MAX },
    { name: 'C-max 1.6 Tdci (115 Hk) Van Forhjulstræk Manuel', result: Model[Make.FORD].C_MAX },
    { name: 'Ford Mondeo 2.0 TDCi 150 HK STAT', result: Model[Make.FORD].MONDEO },
    { name: 'Ford Mondeo', result: Model[Make.FORD].MONDEO }
  ].map(addVinToTest('VS6AAAAAAAA123456')),

  ...[
    { name: 'LDV Deliver7', result: Model[Make.LDV].DELIVER_7 },
    { name: 'LDV Deliver 7', result: Model[Make.LDV].DELIVER_7 },
    { name: 'LDV Deliver9', result: Model[Make.LDV].DELIVER_9 },
    { name: 'LDV Deliver 9', result: Model[Make.LDV].DELIVER_9 },
    { name: 'LDV D90', result: Model[Make.LDV].D90 },
    { name: 'LDV G10', result: Model[Make.LDV].G10 },
    { name: 'LDV MIFA People Mover', result: Model[Make.LDV].MIFA_PEOPLE_MOVER },
    { name: 'LDV Mifa9', result: Model[Make.LDV].MIFA_9 },
    { name: 'LDV Mifa 9', result: Model[Make.LDV].MIFA_9 },
    { name: 'LDV T60', result: Model[Make.LDV].T60 },
    { name: 'LDV V80', result: Model[Make.LDV].V80 }
  ].map(addVinToTest('SEYAAAAAAAA123456')),

  ...[
    { name: 'Mercedes-Benz CiTAN', result: Model[Make.MERCEDES_BENZ].CITAN },
    { name: 'Mercedes-Benz EqV', result: Model[Make.MERCEDES_BENZ].EQV },
    { name: 'Mercedes-Benz Sprinter 316 Cdi Kassevogn Standard', result: Model[Make.MERCEDES_BENZ].SPRINTER },
    { name: 'MERCEDES-B SPRINTER 316 CDI KASSEVOGN  S', result: Model[Make.MERCEDES_BENZ].SPRINTER },
    { name: 'Mercedes Vito', result: Model[Make.MERCEDES_BENZ].VITO },
    { name: 'Mercedes Sprinter', result: Model[Make.MERCEDES_BENZ].SPRINTER },
    { name: 'Mercedes EQB', result: Model[Make.MERCEDES_BENZ].EQB },
    { name: 'Mercedes Benz Sprinter', result: Model[Make.MERCEDES_BENZ].SPRINTER },
    { name: 'Mercedes-benz Vito Kassevogn 111 Cdi Ksv Lang', result: Model[Make.MERCEDES_BENZ].VITO },
    { name: 'Mercedes E', result: Model[Make.MERCEDES_BENZ].E },
    { name: 'Mercedes EQC', result: Model[Make.MERCEDES_BENZ].EQC },
    { name: 'Mercedes GLB', result: Model[Make.MERCEDES_BENZ].GLB },
    { name: 'Mercedes GLE', result: Model[Make.MERCEDES_BENZ].GLE },
    { name: 'Mercedes A', result: Model[Make.MERCEDES_BENZ].A },
    { name: 'Mercedes C', result: Model[Make.MERCEDES_BENZ].C }
  ].map(addVinToTest('WDFAAAAAAAA123456')),

  ...[
    { name: 'Citroen Jumper', result: Model[Make.CITROEN].JUMPER },
    { name: 'Citroen Jumper 2,2', result: Model[Make.CITROEN].JUMPER },
    { name: 'Citroen Jumpy 2,0 Bluehedi 180 hk', result: Model[Make.CITROEN].JUMPY },
    { name: 'Citroen Berlingo', result: Model[Make.CITROEN].BERLINGO },
    { name: 'Citroen C3', result: Model[Make.CITROEN].C3 },
    { name: 'Berlingo Van 1,6 Hdi 92 Hk', result: Model[Make.CITROEN].BERLINGO },
    { name: 'Citroen C-Elysée', result: Model[Make.CITROEN].C_ELYSEE },
    { name: 'Citroen C-Elysee', result: Model[Make.CITROEN].C_ELYSEE }
  ].map(addVinToTest('VS7AAAAAAAA123456')),

  ...[
    { name: 'Fiat Doblo', result: Model[Make.FIAT].DOBLO },
    { name: 'Fiat Ducato', result: Model[Make.FIAT].DUCATO },
    { name: 'Fiat Egea', result: Model[Make.FIAT].EGEA }
  ].map(addVinToTest('ZFAAAAAAAAA123456')),

  ...[
    { name: 'Opel Astra', result: Model[Make.OPEL].ASTRA },
    { name: 'Opel Vivaro', result: Model[Make.OPEL].VIVARO },
    { name: 'Opel Zafira Flexivan', result: Model[Make.OPEL].ZAFIRA },
    { name: 'Opel Vivaro Van', result: Model[Make.OPEL].VIVARO },
    { name: 'Opel Vivaro 2,0 CDTI', result: Model[Make.OPEL].VIVARO },
    { name: 'Opel Combo', result: Model[Make.OPEL].COMBO },
    { name: 'Opel CorSA', result: Model[Make.OPEL].CORSA },
    { name: 'Opel MoKKa-E', result: Model[Make.OPEL].MOKKA_E },
    { name: 'Opel Mokka', result: Model[Make.OPEL].MOKKA }
  ].map(addVinToTest('VN1AAAAAAAA123456')),

  ...[
    { name: 'BMW i3', result: Model[Make.BMW].I3 },
    { name: 'BMW i4', result: Model[Make.BMW].I4 },
    { name: 'BMW i5', result: Model[Make.BMW].I5 },
    { name: 'BMW iX', result: Model[Make.BMW].IX },
    { name: 'BMW ix1', result: Model[Make.BMW].IX1 },
    { name: 'BMW ix2', result: Model[Make.BMW].IX2 },
    { name: 'BMW ix3', result: Model[Make.BMW].IX3 },
    { name: 'BMW 330e', result: Model[Make.BMW]['3'] },
    { name: 'BMW 120 M', result: Model[Make.BMW]['1'] }
  ].map(addVinToTest('WBY41DU01NS510982')),

  ...[
    { name: 'BYD Atto 3', result: Model[Make.BYD].ATTO_3 },
    { name: 'BYD Dolphin', result: Model[Make.BYD].DOLPHIN },
    { name: 'BYD Han', result: Model[Make.BYD].HAN },
    { name: 'BYD Seal', result: Model[Make.BYD].SEAL },
    { name: 'BYD Seal U', result: Model[Make.BYD].SEAL_U },
    { name: 'BYD Tang', result: Model[Make.BYD].TANG }
  ].map(addVinToTest('LGXCF6CD3P2169783')),

  ...[
    { name: 'Polestar 1 HP 233', result: Model[Make.POLESTAR][1] },
    { name: 'Polestar 2 HP 233', result: Model[Make.POLESTAR][2] },
    { name: 'Polestar 3 HP 233', result: Model[Make.POLESTAR][3] },
    { name: 'Polestar 1', result: Model[Make.POLESTAR][1] },
    { name: 'Polestar 2', result: Model[Make.POLESTAR][2] },
    { name: 'Polestar 3', result: Model[Make.POLESTAR][3] }
  ].map(addVinToTest('LPSVSEDEENL046573')),

  ...[
    { name: 'Polestar 1 HP 233', result: Model[Make.POLESTAR][1] },
    { name: 'Polestar 2 HP 233', result: Model[Make.POLESTAR][2] },
    { name: 'Polestar 3 HP 233', result: Model[Make.POLESTAR][3] },
    { name: 'Polestar 1', result: Model[Make.POLESTAR][1] },
    { name: 'Polestar 2', result: Model[Make.POLESTAR][2] },
    { name: 'Polestar 3', result: Model[Make.POLESTAR][3] }
  ].map(addVinToTest('YSMVSEDEENL046573')),

  ...[
    { name: 'Polestar 1 HP 233', result: Model[Make.POLESTAR][1] },
    { name: 'Polestar 2 HP 233', result: Model[Make.POLESTAR][2] },
    { name: 'Polestar 3 HP 233', result: Model[Make.POLESTAR][3] },
    { name: 'Polestar 1', result: Model[Make.POLESTAR][1] },
    { name: 'Polestar 2', result: Model[Make.POLESTAR][2] },
    { name: 'Polestar 3', result: Model[Make.POLESTAR][3] }
  ].map(addVinToTest('YSRVSEDEENL046573')),

  ...[
    { name: 'Maxus Deliver3', result: Model[Make.MAXUS].DELIVER_3 },
    { name: 'Maxus Deliver 3', result: Model[Make.MAXUS].DELIVER_3 },
    { name: 'Maxus Deliver7', result: Model[Make.MAXUS].DELIVER_7 },
    { name: 'Maxus Deliver 7', result: Model[Make.MAXUS].DELIVER_7 },
    { name: 'Maxus Deliver9', result: Model[Make.MAXUS].DELIVER_9 },
    { name: 'Maxus Deliver 9', result: Model[Make.MAXUS].DELIVER_9 },
    { name: 'MaXuS EuNiQ5', result: Model[Make.MAXUS].EUNIQ5 },
    { name: 'Maxus Euniq 5', result: Model[Make.MAXUS].EUNIQ5 },
    { name: 'Maxus Euniq6', result: Model[Make.MAXUS].EUNIQ6 },
    { name: 'Maxus Euniq 6', result: Model[Make.MAXUS].EUNIQ6 },
    { name: 'Maxus Mifa9', result: Model[Make.MAXUS].MIFA_9 },
    { name: 'Maxus Mifa 9', result: Model[Make.MAXUS].MIFA_9 },
    { name: 'Maxus T90 EV', result: Model[Make.MAXUS].T90 },
    { name: 'Maxus T90', result: Model[Make.MAXUS].T90 }
  ].map(addVinToTest('LSHAAAAAAAA123456')),

  ...[
    { name: 'Mazda CX-5', result: Model[Make.MAZDA].CX5 },
    { name: 'Mazda CX5', result: Model[Make.MAZDA].CX5 },
    { name: 'Mazda  2', result: Model[Make.MAZDA][2] },
    { name: 'Mazda  3', result: Model[Make.MAZDA][3] }
  ].map(addVinToTest('JMZAAAAAAAA123456')),

  ...[
    { name: 'Dacia Dokker', result: Model[Make.DACIA].DOKKER },
    { name: 'Dacia Duster', result: Model[Make.DACIA].DUSTER },
    { name: 'DACIA Duster dCi 115 6MT (115 HP)', result: Model[Make.DACIA].DUSTER },
    { name: 'Dacia Sandero', result: Model[Make.DACIA].SANDERO },
    { name: 'DaCIa sPRIng', result: Model[Make.DACIA].SPRING },
    { name: 'DACia JoggeR', result: Model[Make.DACIA].JOGGER },
    { name: 'DaCIa lODGy', result: Model[Make.DACIA].LODGY }
  ].map(addVinToTest('UU1AAAAAAAA123456')),

  ...[
    { name: 'Nissan Ariya', result: Model[Make.NISSAN].ARIYA },
    { name: 'Nissan e-NV200', result: Model[Make.NISSAN].ENV200 },
    { name: 'Nissan Interstar', result: Model[Make.NISSAN].INTERSTAR },
    { name: 'Nissan Juke', result: Model[Make.NISSAN].JUKE },
    { name: 'Nissan Leaf', result: Model[Make.NISSAN].LEAF },
    { name: 'Nissan Navara', result: Model[Make.NISSAN].NAVARA },
    { name: 'Nissan Note', result: Model[Make.NISSAN].NOTE },
    { name: 'Nissan NV400', result: Model[Make.NISSAN].NV400 },
    { name: 'Nissan Primastar', result: Model[Make.NISSAN].PRIMASTAR },
    { name: 'Nissan Qashqai', result: Model[Make.NISSAN].QASHQAI },
    { name: 'Nissan Sylphy', result: Model[Make.NISSAN].SYLPHY },
    { name: 'Nissan Townstar', result: Model[Make.NISSAN].TOWNSTAR },
    { name: 'Nissan X-Trail', result: Model[Make.NISSAN].X_TRAIL }
  ].map(addVinToTest('JN3AAAAAAAA123456')),

  ...[
    { name: 'Nissan NV400', result: Model[Make.NISSAN].NV400 },
    { name: 'Nissan Leaf', result: Model[Make.NISSAN].LEAF },
    { name: 'Nissan Navara', result: Model[Make.NISSAN].NAVARA },
    { name: 'Nissan Sylphy', result: Model[Make.NISSAN].SYLPHY },
    { name: 'Nissan nV-200', result: Model[Make.NISSAN].NV_200 }
  ].map(addVinToTest('SJNAAAAAAAA123456')),

  ...[
    { name: 'Renault Arkana', result: Model[Make.RENAULT].ARKANA },
    { name: 'Renault Austral', result: Model[Make.RENAULT].AUSTRAL },
    { name: 'Renault Captur', result: Model[Make.RENAULT].CAPTUR },
    { name: 'Renault Clio', result: Model[Make.RENAULT].CLIO },
    { name: 'Renault Espace', result: Model[Make.RENAULT].ESPACE },
    { name: 'RENAULT KANGOO 33 KWH AUT', result: Model[Make.RENAULT].KANGOO },
    { name: 'RENAUL KANGOO', result: Model[Make.RENAULT].KANGOO },
    { name: 'Kangoo', result: Model[Make.RENAULT].KANGOO },
    { name: 'Renault Kangoo', result: Model[Make.RENAULT].KANGOO },
    { name: 'Renault Master', result: Model[Make.RENAULT].MASTER },
    { name: 'Renault Megane', result: Model[Make.RENAULT].MEGANE },
    { name: 'Renault Rafale', result: Model[Make.RENAULT].RAFALE },
    { name: 'Renault Scenic', result: Model[Make.RENAULT].SCENIC },
    { name: 'Trafic', result: Model[Make.RENAULT].TRAFIC },
    { name: 'Renault Trafic', result: Model[Make.RENAULT].TRAFIC },
    { name: 'Renaul Trafic', result: Model[Make.RENAULT].TRAFIC },
    { name: '2014 Renault Trafic L1H1 T27 DCi', result: Model[Make.RENAULT].TRAFIC },
    { name: 'Zoe', result: Model[Make.RENAULT].ZOE }
  ].map(addVinToTest('VF1AAAAAAAA123456')),

  ...[{ name: 'Honda HR-V', result: Model[Make.HONDA].HR_V }].map(addVinToTest('NLAAAAAAAAA123456')),

  ...[{ name: 'Hyundai Ioniq 5', result: Model[Make.HYUNDAI].IONIQ5 }].map(addVinToTest('TMAAAAAAAAA123456')),

  ...[{ name: 'Iveco Daily', result: Model[Make.IVECO].DAILY }].map(addVinToTest('ZFCAAAAAAAA123456')),

  ...[
    { name: 'Kia Ceed', result: Model[Make.KIA].CEED },
    { name: 'Kia EV6', result: Model[Make.KIA].EV6 },
    { name: 'Kia EV9', result: Model[Make.KIA].EV9 },
    { name: 'Kia Niro', result: Model[Make.KIA].NIRO }
  ].map(addVinToTest('MS0AAAAAAAA123456')),

  ...[{ name: 'Lamborghini Revuelto', result: Model[Make.LAMBORGHINI].REVUELTO }].map(
    addVinToTest('ZHWAAAAAAAA123456')
  ),

  ...[
    { name: 'Lexus Rz 450e', result: Model[Make.LEXUS].RZ },
    { name: 'Lexus UX', result: Model[Make.LEXUS].UX },
    { name: 'Lexus ES', result: Model[Make.LEXUS].ES },
    { name: 'Lexus NX', result: Model[Make.LEXUS].NX },
    { name: 'Lexus LBX', result: Model[Make.LEXUS].LBX },
    { name: 'Lexus LS', result: Model[Make.LEXUS].LS },
    { name: 'Lexus LC CV', result: Model[Make.LEXUS].LC_CV },
    { name: 'Lexus LC', result: Model[Make.LEXUS].LC }
  ].map(addVinToTest('JTJAABABX0A001483')),
  ...[
    { name: 'Boxster', result: Model[Make.PORSCHE].BOXSTER },
    { name: 'Macan', result: Model[Make.PORSCHE].MACAN },
    { name: 'Taycan', result: Model[Make.PORSCHE].TAYCAN },
    { name: 'Porsche Panamera 4 E-Hybrid (462 hk)', result: Model[Make.PORSCHE].PANAMERA },
    { name: 'Porsche 911', result: Model[Make.PORSCHE][911] }
  ].map(addVinToTest('WP0AAAAAAAA123456')),

  ...[
    { name: 'Hiace 2,5', result: Model[Make.TOYOTA].HIACE },
    { name: 'AuRIS 2,5', result: Model[Make.TOYOTA].AURIS },
    { name: 'ok HiLUX 2,5', result: Model[Make.TOYOTA].HILUX },
    { name: 'Toyota pRoAce Electric 2.0', result: Model[Make.TOYOTA].PROACE_ELECTRIC },
    { name: 'Toyota dyNA 2.1', result: Model[Make.TOYOTA].DYNA },
    { name: 'Toyota CorOLLa 5.3', result: Model[Make.TOYOTA].COROLLA },
    { name: 'Toyota YaRIS 4.2', result: Model[Make.TOYOTA].YARIS },
    { name: 'Toyota PrOAce 4.2', result: Model[Make.TOYOTA].PROACE },
    { name: 'Toyota Sportsvan', result: Model[Make.TOYOTA].SPORTSVAN },
    { name: 'Toyota Aygo X', result: Model[Make.TOYOTA].AYGO_X },
    { name: 'Toyota bZ4X', result: Model[Make.TOYOTA].BZ4X },
    { name: 'Toyota C-HR', result: Model[Make.TOYOTA].C_HR },
    { name: 'Toyota Land Cruiser', result: Model[Make.TOYOTA].LAND_CRUISER },
    { name: 'Toyota RAV4', result: Model[Make.TOYOTA].RAV4 },
    { name: 'Toyota ProACE city electric', result: Model[Make.TOYOTA].PROACE_CITY_ELECTRIC },
    { name: 'Toyota ProACE city', result: Model[Make.TOYOTA].PROACE_CITY }
  ].map(addVinToTest('VNKAAAAAAAA123456')),

  ...[{ name: 'Man TGe car', result: Model[Make.MAN].TGE }].map(addVinToTest('WMAL20S644G128551')),

  ...[
    { name: 'Tesla Model 3', result: Model[Make.TESLA].MODEL_3 },
    { name: 'Tesla 3', result: Model[Make.TESLA].MODEL_3 },
    { name: 'Tesla Model S', result: Model[Make.TESLA].MODEL_S },
    { name: 'Tesla S', result: Model[Make.TESLA].MODEL_S },
    { name: 'Tesla Model X', result: Model[Make.TESLA].MODEL_X },
    { name: 'Tesla X', result: Model[Make.TESLA].MODEL_X },
    { name: 'Tesla Model Y', result: Model[Make.TESLA].MODEL_Y },
    { name: 'Tesla Y', result: Model[Make.TESLA].MODEL_Y }
  ].map(addVinToTest('5YJAAAAAAAA123456')),

  ...[
    { vin: 'WAUAAAAAAAA123456', name: 'NotA4', result: null },
    { vin: 'WVWAAAAAAAA123456', name: 'Bogus CCS', result: null },
    { vin: '', name: 'bogus', result: null },
    { vin: '', name: undefined, result: null }
  ],

  ...[
    { name: 'Ateca', modelCode: 'K11B3C', result: Model[Make.CUPRA].ATECA },
    { name: 'Seat Cupra Leon', modelCode: 'K11C5C', result: Model[Make.CUPRA].LEON },
    { name: 'Tavascan', modelCode: 'KM7BUY', result: Model[Make.CUPRA].TAVASCAN }
  ].map(addVinToTest('VSSABC5FZGR123456')),

  ...[{ name: 'Formentor', result: Model[Make.CUPRA].FORMENTOR }].map(addVinToTest('VSSZZZKMZGR123456')),
  ...[{ name: 'Born', result: Model[Make.CUPRA].BORN }].map(addVinToTest('VSSZZZK1ZGR123456')),
  ...[{ name: 'Tavascan', result: Model[Make.CUPRA].TAVASCAN }].map(addVinToTest('VSSZZZKRZGR123456')),
  ...[{ name: 'Terramar', result: Model[Make.CUPRA].TERRAMAR }].map(addVinToTest('VSSZZZKPZGR123456')),

  ...[
    { name: 'Ateca', result: Model[Make.SEAT].ATECA },
    { name: 'Seat Leon', result: Model[Make.SEAT].LEON },
    { name: 'Formentor', result: Model[Make.SEAT].FORMENTOR },
    { name: 'Born', result: Model[Make.SEAT].BORN }
  ].map(addVinToTest('VSSZZZMMZGR123456')),

  ...[
    { name: 'Amarok 3.0 TDI', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].AMAROK },
    { name: 'Amarok 2.0 TDI', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].AMAROK },
    { name: 'AmK 3.0 TDI', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].AMAROK },
    { name: 'CADDY MAXI WVHIGH 125 CRD6AT', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].CADDY },
    { name: 'Grand California', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].GRAND_CALIFORNIA },
    { name: 'California', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].CALIFORNIA },
    { name: 'VW T6 CARAVELLE LANG CL 2,0 TDI 150', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].CARAVELLE },
    { name: 'Multivan 2,0 TDI', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].MULTIVAN },
    { name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].TRANSPORTER },
    { name: 'TRP PROLINE P-U DH 102HK 340', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].TRANSPORTER },
    { name: 'ID.Buzz', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES]['ID.Buzz'] },
    { name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk', result: Model[Make.VOLKSWAGEN_COMMERCIAL_VEHICLES].CRAFTER }
  ].map(addVinToTest('WV1ZZZAAZFD123456')),

  ...[
    { name: 'Volvo S60', result: Model[Make.VOLVO].S60 },
    { name: 'Volvo V60', result: Model[Make.VOLVO].V60 },
    { name: 'Volvo S90', result: Model[Make.VOLVO].S90 },
    { name: 'Volvo V90', result: Model[Make.VOLVO].V90 },
    { name: 'Volvo XC40', result: Model[Make.VOLVO].XC40 }
  ].map(addVinToTest('YV1AAAAAAAA123456')),

  ...[
    { name: 'XPeng G9', result: Model[Make.XPENG].G9 },
    { name: 'XPeng P7', result: Model[Make.XPENG].P7 }
  ].map(addVinToTest('L1NSPGHB0PA020668')),

  ...[{ name: 'Ligier jS48', result: Model[Make.LIGIER].JS48 }].map(addVinToTest('VJRSPGHB0PA020668')),

  ...[{ name: 'Suzuki alTO', result: Model[Make.SUZUKI].ALTO }].map(addVinToTest('JS2SPGHB0PA020668'))
]

describe('get-model', () => {
  describe('getModel', () => {
    for (const { vin, result, name, modelCode } of cases) {
      it(`resolves model for ${name} (${vin})`, () => {
        expect(getModel({ name, vin, modelCode })).toEqual(result)
      })
    }
  })
})
