const expect = require('unexpected')
const getModel = require('./get-model')

const Make = require('../constants/make')
const Model = require('../constants/model')

const cases = [
  { vin: 'WVWAAAAAAAA123456', name: 'VW Touran CL 1,4TSI 150HK DSG7 BMT 110kW', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'MOVE UP! 1,0MPI 60HK 5G BMT ', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Octavia HB Style 1,4 TSI 150 HK DSG', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'VW PASSAT VAR COMF. 1,6TDI 105HK 6G', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'VW POLO COMF 1,6TDI 90HK 5G BMT 66KW', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'VW move up 1,0MPI 60HK 5G BMT', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'VSSAAAAAAAA123456', name: 'TOLEDO STYLE 1,2 TSI 105HK 6 G', result: Model[Make.SEAT].TOLEDO },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Superb Combi Style 2,0 TDI 150 hk DSG', result: Model[Make.SKODA].SUPERB },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Golf Var Allstar 1,4TSI 125HK 6G BMT', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf ', result: Model[Make.VOLKSWAGEN].GOLF },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Sharan HL 2,0TDI 184hk DSG6 BMT SCR 135k',
    result: Model[Make.VOLKSWAGEN].SHARAN
  },
  { vin: 'WVWAAAAAAAA123456', name: 'ID.4', result: Model[Make.VOLKSWAGEN]['ID.4'] },
  { vin: 'WAUAAAAAAAA123456', name: 'a4', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'NotA4', result: null },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A3', result: Model[Make.AUDI].A3 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi S3', result: Model[Make.AUDI].A3 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi RS5', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q7', result: Model[Make.AUDI].Q7 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi SQ7', result: Model[Make.AUDI].Q7 },
  { vin: 'WVWAAAAAAAA123456', name: 'up!', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen CC', result: Model[Make.VOLKSWAGEN].CC },
  { vin: 'WVWAAAAAAAA123456', name: 'California', result: Model[Make.VOLKSWAGEN].CALIFORNIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Grand California', result: Model[Make.VOLKSWAGEN].GRAND_CALIFORNIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Bogus CCS', result: null },
  { vin: '', name: 'bogus', result: null },
  { vin: '', name: undefined, result: null },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },

  { vin: 'WVWAAAAAAAA123456', name: 'TRP PROLINE P-U DH 102HK 340', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'TRP PROLINE SKÅP 102HK 300', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'TRP KOM 150HK TDI DSG', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'TRP PROLINE P-U EH 102HK 340', result: Model[Make.VOLKSWAGEN].TRANSPORTER },

  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T5 CHASSIS LANG 2,0 TDI 140 HK BMT 6G',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Kort Enka 2,0TDI 84hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk',
    result: Model[Make.VOLKSWAGEN].CRAFTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk',
    result: Model[Make.VOLKSWAGEN].CRAFTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Kort Enka 2,0TDI 84hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T5 CHASSIS LANG 2,0 TDI 140 HK BMT DSG7',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T5 CHASSIS LANG 2,0 TDI 140 HK BMT DSG7',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Crafter 35 Enka 4325mm 2,0 TDI 136 hk',
    result: Model[Make.VOLKSWAGEN].CRAFTER
  },
  // Real examples
  { vin: 'WAUAAAAAAAA123456', name: 'S3', result: Model[Make.AUDI].A3 },
  { vin: 'WVWAAAAAAAA123456', name: 'TOURAN 1,6 TDi', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran ', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'TIGUAN 2,0 BMT SPORT 4M 130 TDI D7A', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VOLKSWAGEN TIGUAN 2.0 SPORT4M103 ', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'T6 Kort Kassevogn 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'Up!', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf Wagon 1.6 CLBM 81 fTDIM5F', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'TOURAN CL 1,4TSI 150HK DSG7 BMT', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'JETTA 1,6 HL', result: Model[Make.VOLKSWAGEN].JETTA },
  { vin: 'WVWZZZE1ZLP015611', name: 'VW ID.3 1st Plus 204HK AUT1 Performance', result: Model[Make.VOLKSWAGEN]['ID.3'] },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW GOLF VAR R-LINE 1,4TSI 150HK DSG7 BMT', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'polo', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: ' Touran', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'GOLF LIMO 1,4 TSI 122 HK', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat Variant 1,4 Tsi Aut.', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran 1.4 Highl 125 TSID7F', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat CC', result: Model[Make.VOLKSWAGEN].CC },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Lang KSV 2,0 TDI 204 hk DSG 4MOTION',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Beetle', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WVWAAAAAAAA123456', name: 'VW high up! 1,0TSI 90HK 5G', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Doka 2,0TDI 150hk 6G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'JETTA', result: Model[Make.VOLKSWAGEN].JETTA },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 7, 1.4TSI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran HL 2,0TDI', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'E-Golf', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'MOVE UP! 1,0MPI 60HK 5G BMT 44KW', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan', result: Model[Make.VOLKSWAGEN].TIGUAN },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'Arteon R-Line 2,0 TDI 110 kW (150 hv) DSG',
    result: Model[Make.VOLKSWAGEN].ARTEON
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Tiguan TDI', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'PASSAT WAG. CLE85 118 D7F ', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'Scirocco', result: Model[Make.VOLKSWAGEN].SCIROCCO },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1.2 TLBMT 77 TSI M6F', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter 35 2,0 TDI 130kW', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'WVWAAAAAAAA123456', name: 'MOVE UP! 1,0MPI 60HK 5G⇥', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter 2,0 177 HK Automat', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat 1,9 Tdi Man Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Touran 1,6 Tdi Bmt', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'TMBAAAAAAAA123456', name: 'Superb', result: Model[Make.SKODA].SUPERB },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Ny Ibiza 5D Style ', result: Model[Make.SEAT].IBIZA },
  { vin: 'WVWAAAAAAAA123456', name: 'vw Touareg', result: Model[Make.VOLKSWAGEN].TOUAREG },
  { vin: 'WVWAAAAAAAA123456', name: 'Up', result: Model[Make.VOLKSWAGEN].UP },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Lang Startline 2,0 TDI 102 5 Gear',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'vw touran', result: Model[Make.VOLKSWAGEN].TOURAN },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Lang Enkeltkabine Alulad 2,0 TDI 102',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf Variant', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'Octavia', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'TMBAAAAAAAA123456', name: 'Citigo', result: Model[Make.SKODA].CITIGO },
  { vin: 'WVWAAAAAAAA123456', name: 'VW GOLF VAR TREND 1,6TDI 105HK 5G BMT 77KW', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA OCTAVIA COMBI ELEGANCE 2,0 TDI 150 HK', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Citigo 1,0', result: Model[Make.SKODA].CITIGO },
  { vin: 'WVWAAAAAAAA123456', name: 'VW BORA 2,0 115 HK 85 KW', result: Model[Make.VOLKSWAGEN].BORA },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Tiguan', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VW TIGUAN 2,0 TDI 140 HK', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan Highline plus', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'TMBAAAAAAAA123456', name: 'fabia', result: Model[Make.SKODA].FABIA },
  { vin: 'WVWAAAAAAAA123456', name: 'GOLF MATCH TDI BMT', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'Yeti Ambition', result: Model[Make.SKODA].YETI },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran Caycaf', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'TMBAAAAAAAA123456', name: 'YETI', result: Model[Make.SKODA].YETI },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 2,0 R', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'Superb 2.0 TDI 140HK Combi', result: Model[Make.SKODA].SUPERB },
  { vin: 'WVWAAAAAAAA123456', name: 'VW TIGUAN 2,0 BMT SPORT TDIM6F', result: Model[Make.VOLKSWAGEN].TIGUAN },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'Tiguan Comfortline PLUS 2,0TDI 150HK DSG7 SCR  ',
    result: Model[Make.VOLKSWAGEN].TIGUAN
  },
  { vin: 'WVWAAAAAAAA123456', name: 'golf 1,9 trend', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golfr32', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 7 1,4', result: Model[Make.VOLKSWAGEN].GOLF },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Lang Startline 2,0 TDI 84 5 Gear',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Crafter ALU L4 Enka 35 TDI 102HK 6G FWD',
    result: Model[Make.VOLKSWAGEN].CRAFTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Crafter ALUL4 Doka35 3UATDI102HK 6G FWD',
    result: Model[Make.VOLKSWAGEN].CRAFTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Doka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'vw passat', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Touran', result: Model[Make.VOLKSWAGEN].TOURAN },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kombi Lang 2,0 TDI 150 hk DSG7',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Kombi Kort 2,0 TDI 150 hk DSG', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kombi Lang Varebil 2,0TDI 150hk 6g 4M',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kort Startline 2,0 TDI 84 5 Gear',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'vw up', result: Model[Make.VOLKSWAGEN].UP },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kombi Lang 2,0 TDI 150 hk DSG7 4MOT',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1,2', result: Model[Make.VOLKSWAGEN].GOLF },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kort Startline 2,0 TDI 102 5 Gear',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW POLO', result: Model[Make.VOLKSWAGEN].POLO },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kombi Kort 2,0 TSI 204 hk DSG7',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'PASSAT WAG. CLBMT 100 M6F', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'TMBAAAAAAAA123456', name: 'Octavia Combi 1,6 TDI Aut.', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'TMBAAAAAAAA123456', name: 'Superb Combi 2.0 Tdi 170 Hk Stationcar Dsg', result: Model[Make.SKODA].SUPERB },
  { vin: 'WVWAAAAAAAA123456', name: 'CADDY MAXI WVHIGH 125 CRD6AT', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'WVWAAAAAAAA123456', name: 'tiguan 2.0', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Vw Polo 1,2 BMT', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'Vw Golf 2,0 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Yeti', result: Model[Make.SKODA].YETI },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Touran comfl 2,0 COMFO 103 TDID6F', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VOLKSWAGEN UP¤ 1.0 MOVE 55 M5F', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'WVWAAAAAAAA123456', name: 'PASSAT WAG. CLB 103 D6F', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'VSSAAAAAAAA123456', name: 'ATECA', result: Model[Make.SEAT].ATECA },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Chassis Zugkopf 2,0 TDI 204 DSG7',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf Cabriolet 1,6 Tdi', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'TOUAREG HYBRI 245 SI A8A', result: Model[Make.VOLKSWAGEN].TOUAREG },
  { vin: 'WVWAAAAAAAA123456', name: 'GOLF 1.4 HLBM 92 TSI M6F', result: Model[Make.VOLKSWAGEN].GOLF },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Chassis Lang Dobbeltkabine DAN 2,0 TD',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat 2.0 tdi', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'TOURAN 1.6BMTTREND 77 TDIM6F', result: Model[Make.VOLKSWAGEN].TOURAN },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Tiguan Comfortline PLUS 2,0 TDI 150 HK 110 kW DSG7',
    result: Model[Make.VOLKSWAGEN].TIGUAN
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan 2.0 Tsi 180 4motion Dsg7', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Vw Touran 2,0 TDI 140 HK', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'TMBAAAAAAAA123456', name: 'Citigo 1.0 Mpi 75 Hk 3-dørs Hatchback', result: Model[Make.SKODA].CITIGO },
  { vin: 'TMBAAAAAAAA123456', name: 'rapid', result: Model[Make.SKODA].RAPID },
  { vin: 'TMBAAAAAAAA123456', name: 'Superb Combi 2.0 TDI 190HK', result: Model[Make.SKODA].SUPERB },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Beetle 1.2 Tsi 105 Hk 77 Kw', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WVWAAAAAAAA123456', name: 'Phaeton 4M5-sea 171fTDIA6A', result: Model[Make.VOLKSWAGEN].PHAETON },
  { vin: 'WAUAAAAAAAA123456', name: 'A6', result: Model[Make.AUDI].A6 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Kort Kassevogn', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat V Conf 1,9TDI 105hk DPF', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 2,0 Tdi Avant', result: Model[Make.AUDI].A4 },
  { vin: 'TMBAAAAAAAA123456', name: 'Octavia Scout 2,0 TDI', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA FABIA', result: Model[Make.SKODA].FABIA },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Chassis Lang Dobb.kab 2,0 TD', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan 2,0 TDI', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WAUAAAAAAAA123456', name: 'A4', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVA.Q. TDI2.0 I4130 A7S', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVANT TDI2.0', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Touareg', result: Model[Make.VOLKSWAGEN].TOUAREG },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 DKLAD Lang Enkeltkabine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVANT TDI 2.0', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 Avant 2.0 TDI', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVANT TDI2.0 I4105 A8M', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVANT TDI2.0 I4130 A8M', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'a4 Avant', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: '8K5CSH A4 Avant TDI 2,0', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 Avant 3.0 Tdi 204 Hk 5-dørs Multitronic', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 Sal.', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 AVANT TDI2.0 I4130 M6S', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 2,0 Tdi Avant.', result: Model[Make.AUDI].A4 },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Ny Ibiza FR 1,5 TSI EVO 150HK 6G', result: Model[Make.SEAT].IBIZA },
  { vin: 'TMBAAAAAAAA123456', name: 'superb l og k', result: Model[Make.SKODA].SUPERB },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan 2.0BMTSPORT4M130 TDID7A', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'BEETLE CAB LIFE 1,4TSI 150HK DSG7 BMT', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WVWAAAAAAAA123456', name: 'GOLF VII 1,6 TDI 110 HK BM ST.CAR', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVANT TDI2.0 I4130 M6S', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A6 Avant 2.8 V6 150Kw A8M', result: Model[Make.AUDI].A6 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 AVANT TDI2.0 I4110 M6S', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A6 Avant 3.0 Tdi 218 Hk 5-dørs S Tronic', result: Model[Make.AUDI].A6 },
  { vin: 'WVWAAAAAAAA123456', name: 'T6', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Rapid Spaceback Tour de France 1,0 TSI 9', result: Model[Make.SKODA].RAPID },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Enka 2,0TSI 150hk 6G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T6 2.0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran 2,0', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'TMBAAAAAAAA123456', name: 'Superb Combi 2,0 Tdi Dsg 190hk', result: Model[Make.SKODA].SUPERB },
  { vin: 'TMBAAAAAAAA123456', name: 'Octavia Scout', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran 1.6 Tdi Bmt 105 Hk Dsg', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Lang Enka 2,0TDI 102hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Kort Enka 2,0TDI 84hk 5G', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'TMBAAAAAAAA123456', name: 'NY FABIA COMBI AMBITION 1,0 TSI 110 HK D', result: Model[Make.SKODA].FABIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Phaeton', result: Model[Make.VOLKSWAGEN].PHAETON },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Lang Startline 2,0 TDI 150HK 6G',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A6 AVANT 3,0 TDI 218 HK 160 KW 7 TRINS S', result: Model[Make.AUDI].A6 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant TDI2.0 105 KW', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: ' Audi A4 Avant 2,0 Tfsi Quattro', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'GOLF 1.2 CLBMT 63 TSI M5F', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 Cabrio 2,0', result: Model[Make.AUDI].A4 },
  {
    vin: 'VSSAAAAAAAA123456',
    name: 'Seat Ateca 2.0 Tdi 190 Hk 140 Kw 5-dørs 4wd Dsg6',
    result: Model[Make.SEAT].ATECA
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat Variant 2,0 tdi', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Octavia RS 2,0 Tdi Aut.', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 2.0 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'Transporter T6 2.0 TDI BMT 4MOTION (204hk)',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Tiguan 2.0 TDI 4MOTION (190hk)', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T6 2.0 TDI BMT (150hk)', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'Transporter T5 2.0 TDI Pickup (140hk)',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Polo CL 1,0TSI 95HK 5G', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'VSSAAAAAAAA123456', name: 'Seat Ateca 1,4 TSI', result: Model[Make.SEAT].ATECA },
  { vin: 'WVWAAAAAAAA123456', name: 'golf plus', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf E-golf', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Golf 7 1.2 Tsi', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'RAPID SPACEBACK AMBITION 1,0 TSI 95 HK', result: Model[Make.SKODA].RAPID },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Touran 1,6 trend', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Golf Limo 1,4 TSI Allstar', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'GOLF PLUS TSICOMFO 118 M6F', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Golf', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A4 AVANT 1,8T 163HK 5 GEAR MAN.', result: Model[Make.AUDI].A4 },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Rapid Hatchback Style 1,0 TSI 110 hk DSG', result: Model[Make.SKODA].RAPID },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Rapid Hatchback ICE 1,0 TSI 110 hk DSG', result: Model[Make.SKODA].RAPID },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'Volkswagen Touran 1.6 Tdi Bmt 105 Hk Dsg 7',
    result: Model[Make.VOLKSWAGEN].TOURAN
  },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Rapid Hatchback ICE 1,0 TSI 95 hk', result: Model[Make.SKODA].RAPID },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Caddy 2.0 T', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA RAPID SPACEBACK AMBITION 1,0 TSI 95 HK', result: Model[Make.SKODA].RAPID },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A6 LIMOUSINE 3,0 TDI 218 HK 160 KW 7 TRI .', result: Model[Make.AUDI].A6 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Tiguan CL PLUS 2,0TDI 150HK DSG7', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen UP! 1,0', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Spaceback Rapid Tour 1,0 95 hk.', result: Model[Make.SKODA].RAPID },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A4 AVA.Q. TDI2.0', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Polo 1,4 Trendline', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf Varint', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf, 1,6 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Polo HL 1,0TSI 115HK DSG7', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'vw golf', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1,2 TSI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW move up! 1,0MPI 60HK 5G', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Rapid Spaceback 1,0 TSI 95 HK', result: Model[Make.SKODA].RAPID },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Citigo Fresh 1,0 MPI 60 hk', result: Model[Make.SKODA].CITIGO },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 CARAVELLE LANG CL 2,0 TDI 150', result: Model[Make.VOLKSWAGEN].CARAVELLE },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T6 2,0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW GOLF 2.0 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Caddy 2.0 TDI', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'WVWAAAAAAAA123456', name: 'Polo van 1,4 TDI', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Superb', result: Model[Make.SKODA].SUPERB },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Touran CL 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'vw golf 1,4 tsi', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter 2.0 TDI', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Fabia FL Ambition 1,0 MPI 75 hk', result: Model[Make.SKODA].FABIA },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A5 COUPÉ 1,8 TFSI 177 HK 130 KW 8 TRINS', result: Model[Make.AUDI].A5 },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Octavia Combi Style 2,0 TSI 190 hk DSG', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A6 2,0 TDI', result: Model[Make.AUDI].A6 },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Fabia Hatchback Ambition 1,0 TSI 95 hk', result: Model[Make.SKODA].FABIA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant 1,8', result: Model[Make.AUDI].A4 },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 Avant 2,0 TDI', result: Model[Make.AUDI].A4 },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Superb Combi Style 1,4 TSI 150 hk DSG', result: Model[Make.SKODA].SUPERB },
  { vin: 'WAUAAAAAAAA123456', name: 'audi a4 avant 2.0 tdi', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Tiguan 2.0 110 TDI', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Caddy 2,0 TDI', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'WVWAAAAAAAA123456', name: 'TOUAREG 3.0 TDI AUT', result: Model[Make.VOLKSWAGEN].TOUAREG },
  { vin: 'WAUAAAAAAAA123456', name: 'A5 Coupé 1,8 TFSI', result: Model[Make.AUDI].A5 },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran 2,o TDI', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Golf HL 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter 2,0 TDI', result: Model[Make.VOLKSWAGEN].CRAFTER },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Tiguan Highline PLUS 2,0TDI 150HK DSG7',
    result: Model[Make.VOLKSWAGEN].TIGUAN
  },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Ny Fabia Combi Ambition 1,0 TSI 95 hk', result: Model[Make.SKODA].FABIA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant Business 40 TDI 190 HK S tro', result: Model[Make.AUDI].A4 },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA OCTAVIA HB RS 2,0 TSI 220HK', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T6 2.0 TDI 150kW', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW GOLF SPORTWAGEN', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Passat Variant 2,0 TDI DSG', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter 35 2,0 TDI 120kW', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'WVWAAAAAAAA123456', name: 'scirocco 2,0 sport tdi', result: Model[Make.VOLKSWAGEN].SCIROCCO },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Polo 1,6 TDI', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI RS 5 COUPÉ 4,2 FSI 450 HK 331 KW QUATTRO', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi a4 lim.', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Touran 2,0 TDI', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A6', result: Model[Make.AUDI].A6 },
  { vin: 'WVWAAAAAAAA123456', name: 'TOUAREG BMT V6TDI 150 TDIA8A', result: Model[Make.VOLKSWAGEN].TOUAREG },
  { vin: 'TMBAAAAAAAA123456', name: 'RAPID SPB AMB TD85/1.6 M5F', result: Model[Make.SKODA].RAPID },
  { vin: 'VSSAAAAAAAA123456', name: 'Saet Ateca 1,5 TSI 150', result: Model[Make.SEAT].ATECA },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Passat Variant R-Line 4Motion 240 HK', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Golf Variant 1.6 TDI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat Variant 2,0', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant 2,0 Tdi Aut.', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat GTE Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Passat Variant 2,0 TDI', result: Model[Make.VOLKSWAGEN].PASSAT },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW CRAFTER CHASSISL3 35 TDI 177HK AUT8G FWD',
    result: Model[Make.VOLKSWAGEN].CRAFTER
  },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant 2.0 Tdi 177 Hk 5-dørs Multitronic', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T6 2.0 TDI 110kw DSG', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW POLO 1,2 TSI 90HK', result: Model[Make.VOLKSWAGEN].POLO },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW Passat Var CL Premium 1,5TSI 150HK DSG7',
    result: Model[Make.VOLKSWAGEN].PASSAT
  },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1,0 cLBM TSI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf Sportsvan', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat 2,0 tdi Variant', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WVWAAAAAAAA123456', name: 'New Beetle', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T6 2.0 TDI 110kW', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW TIGUAN SPORT 2,0TDI 140HK DSG7 BMT 4M', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'TMBAAAAAAAA123456', name: 'CITIGO ELEGA 55/1.0 5-S', result: Model[Make.SKODA].CITIGO },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A6 Avant 3,0 TDi', result: Model[Make.AUDI].A6 },
  { vin: 'VSSAAAAAAAA123456', name: 'Ibiza Style', result: Model[Make.SEAT].IBIZA },
  { vin: 'WVWAAAAAAAA123456', name: 'VOLKSWAGEN TOURAN 1.6BMTHIGHL 77 TDID7F', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA CITIGO ACTIVE GREENTEC 1.0 60HK', result: Model[Make.SKODA].CITIGO },
  {
    vin: 'TMBAAAAAAAA123456',
    name: 'SKODA Octavia Combi Style 1,0 TSI 115 hk 85 kW',
    result: Model[Make.SKODA].OCTAVIA
  },
  {
    vin: 'TMBAAAAAAAA123456',
    name: 'SKODA Octavia Combi Business Line 2,0 TDI 150',
    result: Model[Make.SKODA].OCTAVIA
  },
  {
    vin: 'TMBAAAAAAAA123456',
    name: 'SKODA Superb Combi Business Edition 2,0 TDI 15',
    result: Model[Make.SKODA].SUPERB
  },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA OCTAVIA COMBI AMBITION 1,6 TDI 105 HK', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Arteon', result: Model[Make.VOLKSWAGEN].ARTEON },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 AVANT TDI2.0 I4105 A8M', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Caddy Maxi 2.0 TDI', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Octavia HN B-Line+ 1,5 TSI 150 hk DSG', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Citigo Style Sport 1,0 MPI 60 hk', result: Model[Make.SKODA].CITIGO },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T6 Kort Kassevogn 2,0TDI 102hk 5G',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Touran HL 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'CADDY VAN 1,6TDI 75 HK 55 KW 5 TRINS BMT', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Polo CL Connect 1,0TSI 95HK 5G', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'polo 1,2', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 KaKR', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Octavia', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter, chassi', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter Skåp', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Caddy Maxi', result: Model[Make.VOLKSWAGEN].CADDY },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter Chassi', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf  Alltrack', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA FABIA COMBI GREENLINE 1,2 CR - 55 KW', result: Model[Make.SKODA].FABIA },
  { vin: 'WVWAAAAAAAA123456', name: 'Crafter', result: Model[Make.VOLKSWAGEN].CRAFTER },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Ny Fabia Combi Style Tour 1,0 TSI 95 hk', result: Model[Make.SKODA].FABIA },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Octavia Combi 2,0 TDI', result: Model[Make.SKODA].OCTAVIA },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Arteon Elegance 2,0TSI 190HK DSG7', result: Model[Make.VOLKSWAGEN].ARTEON },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 Avant quattro S-line 2.0 TDI 140kw190ps', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Passat 2,0 tdi', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant Sport 2,0 TFSI 190 HK S tro', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Beetle Cab', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A4 SAL. 2,0 TDI A8M', result: Model[Make.AUDI].A4 },
  { vin: 'VSSAAAAAAAA123456', name: 'Seat Ateca', result: Model[Make.SEAT].ATECA },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1,4 TSI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Beetle Cabriolet', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 Avant 2,0 TDi', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T6 Caravelle', result: Model[Make.VOLKSWAGEN].CARAVELLE },
  { vin: 'WVWAAAAAAAA123456', name: 'TOURAN 2.0 COMFORTLINE', result: Model[Make.VOLKSWAGEN].TOURAN },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Beetle Cariolet', result: Model[Make.VOLKSWAGEN].BEETLE },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1,4', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Golf GTI 2,0TSI 120 HK', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Golf GTI 2,0TSI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen Golf Variant', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'VOLKSWAGEN TIGUAN 2.0 HLBMT4M 132TSID7A', result: Model[Make.VOLKSWAGEN].TIGUAN },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A5 Coupe', result: Model[Make.AUDI].A5 },
  { vin: 'VSSAAAAAAAA123456', name: 'Seat Ateca Exultance 1.4TSP', result: Model[Make.SEAT].ATECA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 2,0 TDI', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW fresh up! 1,0MPI 60HK 5G BMT 44kW', result: Model[Make.VOLKSWAGEN].UP },
  { vin: 'VSSAAAAAAAA123456', name: 'Ibiza', result: Model[Make.SEAT].IBIZA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A4 TDI 3,0', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'PASSAT WAG. CLBMT 176 TDID7A            ', result: Model[Make.VOLKSWAGEN].PASSAT },
  { vin: 'WAUAAAAAAAA123456', name: 'A4 3,0 Tdi', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf Variant 1,0 BlueMotion Technology', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Rapid 1,0', result: Model[Make.SKODA].RAPID },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Polo CL 1,0TSI 95HK DSG7', result: Model[Make.VOLKSWAGEN].POLO },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf GTI', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WVWAAAAAAAA123456', name: 'Golf 1,0', result: Model[Make.VOLKSWAGEN].GOLF },
  { vin: 'WAUAAAAAAAA123456', name: 'S5 Sportback 3,0 TFSI 333 HK', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'S5 Sportback 3,0 TFSI 333 HK 245 KW QUAT', result: Model[Make.AUDI].A5 },
  { vin: 'VSSAAAAAAAA123456', name: 'Arona', result: Model[Make.SEAT].ARONA },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Arona Xcellence 1,6 TDI 95HK DSG7', result: Model[Make.SEAT].ARONA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi S5 Cabriolet', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI RS 5 CABRIOLET 4,2 FSI 450 HK 331 KW QUA', result: Model[Make.AUDI].A5 },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT ARONA', result: Model[Make.SEAT].ARONA },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi S5 CAB.', result: Model[Make.AUDI].A5 },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T-ROC STYLE 1,0TSI 115HK', result: Model[Make.VOLKSWAGEN].TROC },
  { vin: 'VSSAAAAAAAA123456', name: 'LEON', result: Model[Make.SEAT].LEON },
  { vin: 'WAUAAAAAAAA123456', name: 'A5 Sportb TDI2.0', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'A3', result: Model[Make.AUDI].A3 },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI RS Q3 2,5 TFSI 310 HK 228 KW QUATTRO 7 T', result: Model[Make.AUDI].Q3 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A3 Sportsback 1,6', result: Model[Make.AUDI].A3 },
  { vin: 'VSSAAAAAAAA123456', name: 'Leon 2.0 Tsi 280 Hk 206 Kw St. Car Dsg6', result: Model[Make.SEAT].LEON },
  { vin: 'WAUAAAAAAAA123456', name: 'Q7', result: Model[Make.AUDI].Q7 },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT LEON', result: Model[Make.SEAT].LEON },
  { vin: 'WVWAAAAAAAA123456', name: 'T-Roc Sport 2,0TSI 190HK DSG7 4M', result: Model[Make.VOLKSWAGEN].TROC },
  { vin: 'WAUAAAAAAAA123456', name: 'Q5', result: Model[Make.AUDI].Q5 },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Kodiaq', result: Model[Make.SKODA].KODIAQ },
  { vin: 'WVWAAAAAAAA123456', name: 'T-Roc Style 1,0TSI 115HK 6G', result: Model[Make.VOLKSWAGEN].TROC },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A5 SPB QTDI2.0 I4130 A7S', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A3 Sportback', result: Model[Make.AUDI].A3 },
  {
    vin: 'WAUAAAAAAAA123456',
    name: 'Audi Rs Q3 Performance 2.5 Tfsi 367 Hk 5-dørs Quattro S Tronic',
    result: Model[Make.AUDI].Q3
  },
  { vin: 'WAUAAAAAAAA123456', name: 'SQ5', result: Model[Make.AUDI].Q5 },
  { vin: 'WAUAAAAAAAA123456', name: 'A5 CABRIOLET 1,8 TFSI 177 HK 130 KW 8 TR', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'A5', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A3', result: Model[Make.AUDI].A3 },
  { vin: 'VSSAAAAAAAA123456', name: 'Leon 2,0 TDI', result: Model[Make.SEAT].LEON },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI Q5 3,0 TDI AUT.', result: Model[Make.AUDI].Q5 },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI RS Q3 2,5 TFSI 340 HK S TRON', result: Model[Make.AUDI].Q3 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q8 50 TDI qua 286 HK tip', result: Model[Make.AUDI].Q8 },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Leon ST 1,6 TDI DSG STYLE', result: Model[Make.SEAT].LEON },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI Q7', result: Model[Make.AUDI].Q7 },
  { vin: 'WAUAAAAAAAA123456', name: 'A5 Cabriolet 1,8 TFSI', result: Model[Make.AUDI].A5 },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter T5 2.0 TDI', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Volkswagen T-Roc', result: Model[Make.VOLKSWAGEN].TROC },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q5 3,0 TDI', result: Model[Make.AUDI].Q5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A3 SB Sp. Lim. 35 TDI 150 HK S tro', result: Model[Make.AUDI].A3 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T-Roc Style 1,5TSI 150HK DSG7 EVO ACT', result: Model[Make.VOLKSWAGEN].TROC },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q5', result: Model[Make.AUDI].Q5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q8', result: Model[Make.AUDI].Q8 },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI Q7 3,0 TDI 211HK QUATTRO TIPTRONIC EU4 (2009)', result: Model[Make.AUDI].Q7 },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A3 SPORTBACK AMBIENTE 1,4 TFSI 140 HK 10', result: Model[Make.AUDI].A3 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q2', result: Model[Make.AUDI].Q2 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A3 SB Sp. Lim. 35 TFSI 150 HK S tro', result: Model[Make.AUDI].A3 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A5 SB Sport 40 TDI 190 HK S tro', result: Model[Make.AUDI].A5 },
  { vin: 'VSSAAAAAAAA123456', name: 'Seat Leon FR 2,0 TSI', result: Model[Make.SEAT].LEON },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Kodiaq Style 2,0 TDI 150 hk 4x4', result: Model[Make.SKODA].KODIAQ },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter skåp', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A5', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI Q5 QUAT. 3,0 TDI V6', result: Model[Make.AUDI].Q5 },
  { vin: 'WAUAAAAAAAA123456', name: 'A5 Cabriolet', result: Model[Make.AUDI].A5 },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi Q3 Adv. PRE 35 TFSI 150 HK S tro', result: Model[Make.AUDI].Q3 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T-Cross Life 1,0TSI 115HK DSG7', result: Model[Make.VOLKSWAGEN].TCROSS },
  { vin: 'WVWAAAAAAAA123456', name: 'VW T-Cross Life 1,0TSI 95HK 5G', result: Model[Make.VOLKSWAGEN].TCROSS },
  { vin: 'VSSAAAAAAAA123456', name: 'Seat Leon St.car.', result: Model[Make.SEAT].LEON },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Leon ST Style Premium 1,6 TDI 115HK DSG7', result: Model[Make.SEAT].LEON },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Leon Sport Tourer ST 1.2 TSI DSG', result: Model[Make.SEAT].LEON },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI RS 4 AVANT 4,2 FSI 450 HK 331 KW QUATTRO', result: Model[Make.AUDI].A4 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Transporter T5GP', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A5, 1,8 TFSI', result: Model[Make.AUDI].A5 },
  { vin: 'WVWAAAAAAAA123456', name: 'Transporter 2.0 TDI 75kw', result: Model[Make.VOLKSWAGEN].TRANSPORTER },
  { vin: 'WVWAAAAAAAA123456', name: 'Sharan succ. HLBMT 130 CRD6F', result: Model[Make.VOLKSWAGEN].SHARAN },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi RS 3 Sportback 2,5TFSI 367hk S-tron qu', result: Model[Make.AUDI].A3 },
  { vin: 'WVWAAAAAAAA123456', name: 'Caravelle', result: Model[Make.VOLKSWAGEN].CARAVELLE },
  { vin: 'WVWAAAAAAAA123456', name: 'Sharan 2,0 TDI', result: Model[Make.VOLKSWAGEN].SHARAN },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi A7', result: Model[Make.AUDI].A7 },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Sharan', result: Model[Make.VOLKSWAGEN].SHARAN },
  {
    vin: 'WAUAAAAAAAA123456',
    name: 'Audi RS7 SPORTB. Q4.0 V8412 A8 Audi RS7 SPORTB. Q4.0 V8412 A8',
    result: Model[Make.AUDI].A7
  },
  { vin: 'WVWAAAAAAAA123456', name: 'VW Sharan 2,0 tdi dsg 170 hk', result: Model[Make.VOLKSWAGEN].SHARAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Sharan', result: Model[Make.VOLKSWAGEN].SHARAN },
  { vin: 'WVWAAAAAAAA123456', name: 'Amarok 3.0 TDI', result: Model[Make.VOLKSWAGEN].AMAROK },
  { vin: 'WVWAAAAAAAA123456', name: 'Amarok 2.0 TDI', result: Model[Make.VOLKSWAGEN].AMAROK },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI A7 SPORTBACK 3,0 TFSI QUA 333 HK S TRO', result: Model[Make.AUDI].A7 },
  { vin: 'WAUAAAAAAAA123456', name: 'S7 Sportback 4,0 TFSI', result: Model[Make.AUDI].A7 },
  { vin: 'WVWAAAAAAAA123456', name: 'Caravelle 2,0 TDI', result: Model[Make.VOLKSWAGEN].CARAVELLE },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi RS 3 2,5 TFSI', result: Model[Make.AUDI].A3 },
  { vin: 'TMBAAAAAAAA123456', name: 'Skoda Karoq', result: Model[Make.SKODA].KAROQ },
  { vin: 'WVWAAAAAAAA123456', name: 'Multivan 2,0 TDI', result: Model[Make.VOLKSWAGEN].MULTIVAN },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Tarraco XC 7S 2,0 TSI 190HK 4x4 DSG7', result: Model[Make.SEAT].TARRACO },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Tarraco XC 7S 2,0 TDI 150HK 6G', result: Model[Make.SEAT].TARRACO },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Tarraco Xcellence 2,0 TSI 190HK 4x4 DSG7', result: Model[Make.SEAT].TARRACO },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT Tarraco XC 7S 1,5 TSI 150HK 6G', result: Model[Make.SEAT].TARRACO },
  { vin: 'WVWAAAAAAAA123456', name: 'VW SHARAN HLBMT 162 TSID6F', result: Model[Make.VOLKSWAGEN].SHARAN },
  { vin: 'TMBAAAAAAAA123456', name: 'SKODA Karoq Style 1,5 TSI 150 hk DSG', result: Model[Make.SKODA].KAROQ },
  { vin: 'WVWAAAAAAAA123456', name: 'Amarok 3.0 V6', result: Model[Make.VOLKSWAGEN].AMAROK },
  { vin: 'WAUAAAAAAAA123456', name: 'Audi RS6 Avant 4,0 FSI 550 HK', result: Model[Make.AUDI].A6 },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT ALTEA XL STYLANCE 1.8 TSI 160HK', result: Model[Make.SEAT].ALTEA },
  { vin: 'WAUAAAAAAAA123456', name: 'AUDI RS 6 AVANT 4,0 TFSI 560 HK 412 KW QUATTR', result: Model[Make.AUDI].A6 },
  { vin: 'VSSAAAAAAAA123456', name: 'Alhambra', result: Model[Make.SEAT].ALHAMBRA },
  { vin: 'VSSAAAAAAAA123456', name: 'SEAT BoRn', result: Model[Make.SEAT].BORN },
  { vin: 'VF3AAAAAAAA123456', name: 'Expert 1.6 Bluehdi 115 Hk L2', result: Model[Make.PEUGEOT].EXPERT },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford C-max', result: Model[Make.FORD].C_MAX },
  { vin: 'VS7AAAAAAAA123456', name: 'Citroen Jumper', result: Model[Make.CITROEN].JUMPER },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford Transit', result: Model[Make.FORD].TRANSIT },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford Focus', result: Model[Make.FORD].FOCUS },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford S-Max', result: Model[Make.FORD].S_MAX },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford fiesTA', result: Model[Make.FORD].FIESTA },
  { vin: 'ZFAAAAAAAAA123456', name: 'Fiat Doblo', result: Model[Make.FIAT].DOBLO },
  { vin: 'VNVAAAAAAAA123456', name: 'Nissan NV400', result: Model[Make.NISSAN].NV400 },
  { vin: 'ZFAAAAAAAAA123456', name: 'Fiat Ducato', result: Model[Make.FIAT].DUCATO },
  { vin: 'VF3AAAAAAAA123456', name: 'Peugeot Partner L1 BlueHDi 75', result: Model[Make.PEUGEOT].PARTNER },
  { vin: 'VN1AAAAAAAA123456', name: 'Opel Vivaro', result: Model[Make.OPEL].VIVARO },
  { vin: 'VN1AAAAAAAA123456', name: 'Opel Zafira Flexivan', result: Model[Make.OPEL].ZAFIRA },
  { vin: 'VN1AAAAAAAA123456', name: 'Opel Vivaro Van', result: Model[Make.OPEL].VIVARO },
  { vin: 'VF3AAAAAAAA123456', name: 'Peugeot Partner', result: Model[Make.PEUGEOT].PARTNER },
  {
    vin: 'VS6AAAAAAAA123456',
    name: 'Ford Transit 2.2 Tdci (140 Hk) 350m Van Fwd Manuel',
    result: Model[Make.FORD].TRANSIT
  },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford Transit 2.2 Tdci (140 Hk) Kassevogn Man.', result: Model[Make.FORD].TRANSIT },
  {
    vin: 'WDFAAAAAAAA123456',
    name: 'Mercedes-benz Vito Kassevogn 111 Cdi Ksv Lang',
    result: Model[Make.MERCEDES_BENZ].VITO
  },
  { vin: 'VF3AAAAAAAA123456', name: 'Peugeot Expert 2.0 Bluehdi 120 Hk L3', result: Model[Make.PEUGEOT].EXPERT },
  { vin: 'WDFAAAAAAAA123456', name: 'Mercedes Benz Sprinter', result: Model[Make.MERCEDES_BENZ].SPRINTER },
  { vin: 'VS7AAAAAAAA123456', name: 'Citroen Jumper 2,2', result: Model[Make.CITROEN].JUMPER },
  { vin: 'WDFAAAAAAAA123456', name: 'Mercedes Sprinter', result: Model[Make.MERCEDES_BENZ].SPRINTER },
  { vin: 'UU1AAAAAAAA123456', name: 'Dacia Dokker', result: Model[Make.DACIA].DOKKER },
  { vin: 'UU1AAAAAAAA123456', name: 'Dacia Duster', result: Model[Make.DACIA].DUSTER },
  { vin: 'UU1AAAAAAAA123456', name: 'DACIA Duster dCi 115 6MT (115 HP)', result: Model[Make.DACIA].DUSTER },
  { vin: 'WDFAAAAAAAA123456', name: 'Mercedes Vito', result: Model[Make.MERCEDES_BENZ].VITO },
  { vin: 'VF1AAAAAAAA123456', name: 'RENAULT KANGOO 33 KWH AUT', result: Model[Make.RENAULT].KANGOO },
  {
    vin: 'WDFAAAAAAAA123456',
    name: 'MERCEDES-B SPRINTER 316 CDI KASSEVOGN  S',
    result: Model[Make.MERCEDES_BENZ].SPRINTER
  },
  { vin: 'WDFAAAAAAAA123456', name: 'MERCEDES-B LASTBIL SOMETHING', result: Model[Make.MERCEDES_BENZ].LASTBIL },
  { vin: 'VF1AAAAAAAA123456', name: 'RENAUL KANGOO', result: Model[Make.RENAULT].KANGOO },
  { vin: 'ZFCAAAAAAAA123456', name: 'Iveco Daily', result: Model[Make.IVECO].DAILY },
  { vin: 'VS7AAAAAAAA123456', name: 'Citroen Jumpy 2,0 Bluehedi 180 hk', result: Model[Make.CITROEN].JUMPY },
  { vin: 'VF3AAAAAAAA123456', name: 'Peugeot Partner Van 1.6 Bluehdi 100 Hk L2', result: Model[Make.PEUGEOT].PARTNER },
  {
    vin: 'VS6AAAAAAAA123456',
    name: 'Ford Transit Custom 2.2 Tdci (100 Hk) 270 L1 Van Forhjulstræk Manuel',
    result: Model[Make.FORD].TRANSIT
  },
  { vin: 'VS7AAAAAAAA123456', name: 'Citroen Berlingo', result: Model[Make.CITROEN].BERLINGO },
  { vin: 'VF1AAAAAAAA123456', name: 'Renault Master', result: Model[Make.RENAULT].MASTER },
  { vin: 'VN1AAAAAAAA123456', name: 'Opel Vivaro 2,0 CDTI', result: Model[Make.OPEL].VIVARO },
  {
    vin: 'WDFAAAAAAAA123456',
    name: 'Mercedes-Benz Sprinter 316 Cdi Kassevogn Standard',
    result: Model[Make.MERCEDES_BENZ].SPRINTER
  },
  { vin: 'VF1AAAAAAAA123456', name: 'Kangoo', result: Model[Make.RENAULT].KANGOO },
  { vin: 'VF1AAAAAAAA123456', name: 'Renault Kangoo', result: Model[Make.RENAULT].KANGOO },
  { vin: 'VF1AAAAAAAA123456', name: 'Trafic', result: Model[Make.RENAULT].TRAFIC },
  { vin: 'VF1AAAAAAAA123456', name: 'Renault Trafic', result: Model[Make.RENAULT].TRAFIC },
  { vin: 'VF1AAAAAAAA123456', name: 'Renaul Trafic', result: Model[Make.RENAULT].TRAFIC },
  { vin: 'VF1AAAAAAAA123456', name: '2014 Renault Trafic L1H1 T27 DCi', result: Model[Make.RENAULT].TRAFIC },
  { vin: 'VF3AAAAAAAA123456', name: 'PEUGEOT EXPERT BlueHDi 120 L3', result: Model[Make.PEUGEOT].EXPERT },
  {
    vin: 'VS6AAAAAAAA123456',
    name: 'Ny C-max 2.0 tdci (170 Hk) Van Forhjulstræk Automatisk',
    result: Model[Make.FORD].C_MAX
  },
  { vin: 'VF3AAAAAAAA123456', name: 'Partner Van ⇥1,6 E-hdi L1', result: Model[Make.PEUGEOT].PARTNER },
  { vin: 'VF3AAAAAAAA123456', name: 'Expert Varebil G9 2,0 Hdi 128 Hk L1h1', result: Model[Make.PEUGEOT].EXPERT },
  { vin: 'VS7AAAAAAAA123456', name: 'Berlingo Van 1,6 Hdi 92 Hk', result: Model[Make.CITROEN].BERLINGO },
  { vin: 'VS6AAAAAAAA123456', name: 'C-max Van 1,6 Tdci', result: Model[Make.FORD].C_MAX },
  { vin: 'VS6AAAAAAAA123456', name: 'Focus C-max 1,6', result: Model[Make.FORD].C_MAX },
  { vin: 'VNKAAAAAAAA123456', name: 'Hiace 2,5', result: Model[Make.TOYOTA].HIACE },
  { vin: 'VNKAAAAAAAA123456', name: 'AuRIS 2,5', result: Model[Make.TOYOTA].AURIS },
  { vin: 'VNKAAAAAAAA123456', name: 'ok HiLUX 2,5', result: Model[Make.TOYOTA].HILUX },
  { vin: 'VNKAAAAAAAA123456', name: 'Toyota pRoAce Electric 2.0', result: Model[Make.TOYOTA].PROACE_ELECTRIC },
  { vin: 'VNKAAAAAAAA123456', name: 'Toyota dyNA 3.0', result: Model[Make.TOYOTA].DYNA },
  { vin: 'VS6AAAAAAAA123456', name: 'C-max 1.6 Tdci (115 Hk) Van Forhjulstræk Manuel', result: Model[Make.FORD].C_MAX },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford Mondeo 2.0 TDCi 150 HK STAT', result: Model[Make.FORD].MONDEO },
  { vin: 'VS6AAAAAAAA123456', name: 'Ford Mondeo', result: Model[Make.FORD].MONDEO },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW T5 CHASSIS LANG 2,0 TDI 140HK BMT 4MOT',
    result: Model[Make.VOLKSWAGEN].TRANSPORTER
  },
  {
    vin: 'WVWAAAAAAAA123456',
    name: 'VW ComfortLine 2,0 TDI',
    result: Model[Make.VOLKSWAGEN].COMFORTLINE
  },
  { vin: 'WMAL20S644G128551', name: 'Man TGe car', result: Model[Make.MAN].TGE }
]

describe('get-model', () => {
  describe('getModel', () => {
    for (const { vin, name, result } of cases) {
      it(`resolves model for ${name} (${vin})`, () => {
        expect(getModel({ vin, name }), 'to equal', result)
      })
    }
  })
})
