module.exports = {
  ALFA_ROMEO: 'Alfa Romeo',
  ASTON_MARTIN: 'Aston Martin',
  AUDI: 'Audi',
  BMW: 'BMW',
  BENTLEY: 'Bentley',
  BUGATTI: 'Bugatti',
  BUICK: 'Buick',
  CADILLAC: 'Cadillac',
  CHEVROLET: 'Chevrolet',
  CHRYSLER: 'Chrysler',
  CITROEN: 'Citroën',
  DACIA: 'Dacia',
  DAF: 'DAF',
  DAEWOO: 'Daewoo',
  DAIHATSU: 'Daihatsu',
  DELOREAN: 'DeLorean',
  DODGE: 'Dodge',
  DUCATI: 'Ducati',
  FERRARI: 'Ferrari',
  FIAT: 'Fiat',
  FORD: 'Ford',
  FREIGHTLINER: 'Freightliner',
  GENERAL_MOTORS: 'General Motors',
  HARLEY_DAVIDSON: 'Harley Davidson',
  HONDA: 'Honda',
  HYUNDAI: 'Hyundai',
  IKARUS: 'Ikarus',
  ISUZU: 'Isuzu',
  IVECO: 'Iveco',
  JAGUAR: 'Jaguar',
  JEEP: 'Jeep',
  KAWASAKI: 'Kawasaki',
  KENWORTH: 'Kenworth',
  KIA: 'Kia',
  KOENIGSEGG: 'Koenigsegg',
  LADA: 'Lada',
  LAMBORGHINI: 'Lamborghini',
  LANCIA: 'Lancia',
  LAND_ROVER: 'Land Rover',
  LINCOLN: 'Lincoln',
  LOTUS: 'Lotus',
  MAN: 'MAN',
  MG: 'MG',
  MINI: 'MINI',
  MACK: 'Mack',
  MASERATI: 'Maserati',
  MAZDA: 'Mazda',
  MCLAREN: 'McLaren',
  MERCEDES_BENZ: 'Mercedes-Benz',
  MERCURY: 'Mercury',
  MITSUBISHI: 'Mitsubishi',
  NISSAN: 'Nissan',
  NOVA: 'Nova',
  OLDSMOBILE: 'Oldsmobile',
  OPEL: 'Opel',
  PEUGEOT: 'Peugeot',
  PLYMOUTH: 'Plymouth',
  PONTIAC: 'Pontiac',
  PORSCHE: 'Porsche',
  RENAULT: 'Renault',
  ROLLS_ROYCE: 'Rolls Royce',
  SAAB: 'Saab',
  SATURN: 'Saturn',
  SCANIA: 'Scania',
  SEAT: 'SEAT',
  SKODA: 'Škoda',
  SMART: 'smart',
  SOLARIS: 'Solaris',
  SSANGYONG: 'SsangYong',
  SUBARU: 'Subaru',
  SUZUKI: 'Suzuki',
  TESLA: 'Tesla',
  TOYOTA: 'Toyota',
  TRIUMPH: 'Triumph',
  VOLKSWAGEN: 'Volkswagen',
  VOLVO: 'Volvo',
  YAMAHA: 'Yamaha',
  WESTERN_STAR: 'Western Star'
}
