import { validateVin } from './validate-vin'

describe('validators/validate-vin', () => {
  it('validateVin', () => {
    expect(validateVin('ZCFC35A3205853011')).toBe(true)
    expect(validateVin('WVWZZZAAZAD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZBD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZCD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZDD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZED123456')).toBe(true)
    expect(validateVin('WVWZZZAAZFD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZGD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZHD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZID123456')).toBe(false)
    expect(validateVin('WVWZZZAAZJD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZKD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZLD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZMD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZND123456')).toBe(true)
    expect(validateVin('WVWZZZAAZOD123456')).toBe(false)
    expect(validateVin('WVWZZZAAZPD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZQD123456')).toBe(false)
    expect(validateVin('WVWZZZAAZRD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZSD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZTD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZUD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZVD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZWD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZXD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZYD123456')).toBe(true)
    expect(validateVin('WVWZZZAAZZD123456')).toBe(false)
    expect(validateVin('WVWZZZAAZ0D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ1D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ2D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ3D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ4D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ5D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ6D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ7D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ8D123456')).toBe(true)
    expect(validateVin('WVWZZZAAZ9D123456')).toBe(true)
    expect(validateVin('AAAAAAAAAaAAAAAAA')).toBe(true)
    expect(validateVin('AAAAAAAAAZAAAAAAA')).toBe(false)
    expect(validateVin('VSS-invalid-vin')).toBe(false)
    expect(validateVin('bogus')).toBe(false)

    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    expect(validateVin()).toBe(false)
  })
})
